import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'kz' | 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  kz: {
    'select_language': 'Тілді таңдаңыз',
    'welcome': 'Kendala әлеміне қош келдіңіз',
    'start_journey': 'Саяхатты бастау',
    'skip_intro': 'Кіріспені өткізу',
    'next_chapter': 'Келесі кезең',
    'chapter': 'Кезең',
    'winter': 'Қыс',
    'spring': 'Көктем',
    'summer': 'Жаз',
    'autumn': 'Күз',
    'winter_tagline': 'Тыныштық мекені',
    'spring_tagline': 'Тіршілік бастауы',
    'summer_tagline': 'Күн шуағы',
    'autumn_tagline': 'Алтын уақыт',
    'winter_desc': 'Алатау шыңдары',
    'spring_desc': 'Жасыл жайлау',
    'summer_desc': 'Мөлдір көлдер',
    'autumn_desc': 'Сары алтын күз',
    'winter_full': 'Тау шаңғысы мен табиғат тыныштығы.',
    'spring_full': 'Дала гүлдеп, табиғат оянған шақ.',
    'summer_full': 'Көлсай мен Қайыңдының сұлулығы.',
    'autumn_full': 'Алтай мен Тянь-Шань ормандарының алтын түсі.',
    'hero_brand_tagline': 'ҚАЗАҚСТАНДЫ ЗЕРТТЕ // КӨШПЕНДІЛЕР МҰРАСЫ',
    'hero_main_tagline': 'Ұлы даланың сұлулығын ашыңыз',
    'discover_kz': 'Қазақстанды тану',
    'system_active': 'Жүйе қосылды',
    'mode': 'күйі',
    'digitizing_steppe': 'Цифрлы Дала',
    'tools_kit': 'Құралдар',
    'digital_tools_desc': 'Саяхатшыға қажетті заттар.',
    'explore': 'Зерттеу',
    'index_02_title': 'Жинақ',
    'index_02_desc': 'Табиғаттың шынайы көрінісі.',
    'featured_location': 'Таңдаулы мекен',
    'read_more': 'Толығырақ',
    'local_species': 'Жануарлар әлемі',
    'home': 'Басты бет',
    'places': 'Мекендер',
    'places_title': 'Киелі мекендер тізімі',
    'places_year_round': 'Жыл бойы',
    'regions': 'Аймақтар',
    'tours': 'Турлар',
    'map': 'Карта',
    'ai': 'AI Гид',
    'culture': 'Мәдениет',
    'history': 'Тарих',
    'news': 'Жаңалықтар',
    'profile': 'Профиль',
    'tools': 'Құралдар',
    'stays': 'Қонақ үйлер',
    'planner': 'Жоспарлаушы',
    'guide': 'Нұсқаулық',
    'login': 'Кіру',
    'select_season': 'Мезгілді таңдаңыз',
    'coordinates': 'Координаттар',
    'altitude': 'Биіктік',
    'difficulty': 'Қиындық',
    'hard': 'Қиын',
    'medium': 'Орташа',
    'easy': 'Оңай',
    'view_analysis': 'Талдау',
    'instrument_analysis': 'Аспап туралы',
    'history_significance': 'Тарихи маңызы',
    'back_to_main': 'Басты бетке оралу',
    'menu': 'Мәзір',
    'system': 'Жүйе',
    'change_season': 'Мезгілді ауыстыру',
    'ai_guide_title': 'Ақылды көмекші',
    'ai_guide_desc': 'Саяхатыңызды жоспарлауға көмектеседі.',
    'digital_map_title': 'Интерактивті карта',
    'digital_map_desc': 'Барлық бағыттар мен соқпақтар.',
    'culture_lib_title': 'Мәдени мұра',
    'culture_lib_desc': 'Тарих пен дәстүр қоры.',
    'expeditions': 'Экспедициялар',
    'traditions': 'Дәстүрлер',
    'journal': 'Саяхатшы күнделігі',
    'weather_tab': 'Ауа райы',
    'survival_tab': 'Қауіпсіздік',
    'reality_tab': 'Қашықтық',
    'culture_tab': 'Мәдениет',
    'offline_tab': 'Офлайн',
    'road_closure_title': 'Жол жағдайы',
    'scanning_satellites': 'Байланыс орнату...',
    'travel_difficulty': 'Бағыт қиындығы',
    'emergency_contacts_active': 'Шұғыл байланыс',
    'steppe_survival_packing': 'Қажетті жабдықтар',
    'reality_check_title': 'Уақыт пен жол',
    'add_route': 'Бағыт қосу',
    'offline_safe_trip': 'Қауіпсіздік ережелері',
    'download_itinerary': 'Жүктеп алу',
    'from': 'Қайдан',
    'to': 'Қайда',
    'distance': 'Қашықтық (км)',
    'air_travel': 'Ұшақ',
    'talgo_express': 'Тальго',
    'standard_train': 'Пойыз',
    'hours': 'сағат',
    'reset': 'Тазалау',
    'field_logistics': 'Логистика',
    'device_status': 'Құрылғы',
    'satellite_stable': 'GPS белсенді',
    'nomadic_toolkit': 'Саяхат құралдары',
    'nomadic_arsenal': 'Көшпенді Жабдығы',
    'prep_protocol': 'Дайындық Хаттамасы',
    'current_loadout': 'Ағымдағы Жүк',
    'nomad_quote': '"Құралы жоқ көшпенді — желі жоқ дала сияқты: тымырсық және тез ұмытылады."',
    'whispering_steppe': 'Дала үні',
    'nomadic_ethos': 'Көшпенді рухы',
    'land_remembers': 'Тарих ізі',
    'philosophy_quote': '"Жол – бұл жай ғана қашықтық емес, бұл өзіңді тану."',
    'our_philosophy': 'Біздің философия',
    'ways_of_travel': 'Саяхат түрлері',
    'ways_of_travel_desc': 'Қазақстанның әртүрлі бағыттарын ашыңыз.',
    'chronos': 'Уақыт',
    'four_acts': 'Мезгілдер коллекциясы',
    'phase': 'Кезең',
    'current': 'Қазір',
    'sacred_landmark': 'Көрікті жер',
    'elevation_label': 'Биіктік',
    'difficulty_label': 'Деңгей',
    'your_journey_awaits': 'Сапарыңызды бастаңыз',
    'journey_quote': 'Әр сапар – жаңа оқиға.',
    'trip_planner_title': 'Жол салу',
    'enter_trip_name': 'Сапар атауын енгізіңіз',
    'failed_save': 'Сақтау сәтсіз',
    'failed_delete': 'Жою сәтсіз',
    'trip_name_placeholder': 'Жаңа сапар',
    'trip_unnamed': 'Атаусыз',
    'save_trip': 'Сақтау',
    'saving': 'Сақтауда...',
    'saved_trips': 'Сақталған сапарлар',
    'create_new_trip': 'Жаңа бастау',
    'no_trips': 'Тек бос жол',
    'load_trips': 'Жаңарту',
    'delete_trip_confirm': 'Осы жолды жою керек пе?',
    'trip_deleted': 'Жол жойылды',
    'trip_saved': 'Жол сақталды',
    'trip_switched': 'Жол ауысты',
    'new_trip_created': 'Жаңа жол ашылды',
    'add_day': 'Күн қосу',
    'day': 'Күн',
    'phase_label': 'Кезең',
    'events_count': 'оқиға',
    'add_activity': 'Оқиға қосу',
    'timeline_empty': 'Уақыт жолағы бос',
    'activity_type_travel': 'Қозғалыс',
    'activity_type_stay': 'Тұру',
    'activity_type_activity': 'Іс-әрекет',
    'activity_type_food': 'Ас-су',
    'activity_name': 'Атауы',
    'activity_location': 'Орны',
    'activity_time': 'Уақыты',
    'activity_cost': 'Бағасы',
    'activity_notes': 'Ескертпе',
    'activity_submit': 'Қосу',
    'total_budget': 'Бюджет',
    'edit_activity': 'Өзгерту',
    'delete_activity': 'Жою',
    'pending_activity_added': 'Қосылды',
    'rating': 'Рейтинг',
    'email_label': 'Пошта',
    'region': 'Аймақ',
    'duration': 'Ұзақтығы',
    'price': 'Бағасы',
    'included': 'Қамтылған',
    'not_included': 'Қамтылмаған',
    'what_to_bring': 'Не алу керек',
    'book_now': 'Брондау',
    'view_details': 'Толығырақ',
    'days_label': 'күн',
    'day_label': 'Күн',
    'select_trip': 'Сапарды таңдаңыз',
    'current_draft': 'Ағымдағы жоба',
    'confirm': 'Растау',
    'add_to_planner_desc': 'Бұл тур сіздің жоспарыңызға {day}-күннен бастап қосылады. Кейінгі жоспарларыңыз автоматты түрде жылжиды.',

    'tool_constructor_label': 'Саяхат Құрастырушы',
    'tool_constructor_desc': 'Толық саяхат жоспарын қадамдап құрыңыз.',
    'tool_hidden_gems_label': 'Жасырын Гауһарлар',
    'tool_hidden_gems_desc': 'Тек жергілікті тұрғындар білетін құпия жерлер.',
    'tool_translator_label': 'Көшпенді Тілмәші',
    'tool_translator_desc': 'Жергілікті сөз тіркестерімен тіл табысыңыз.',
    'tool_horizon_label': 'Көкжиек Жолы',
    'tool_horizon_desc': 'Ежелгі соқпақтар мен көшпенділер жолын іздеу.',
    'tool_nomad_label': 'Жолаушы Жабдығы',
    'tool_nomad_desc': 'Алдағы жолға қажетті құралдарды табу.',
    'tool_budget_label': 'Сапар Салмағы',
    'tool_budget_desc': 'Жолға қажетті ресурстарды бағалау.',
    
    'field_destination': 'Облыс / Аймақ',
    'ph_destination': 'мыс. Алматы немесе Маңғыстау облысы',
    'field_duration': 'Қанша уақытқа?',
    'ph_duration': 'мыс. 5 күн',
    'field_budget': 'Бюджет деңгейі',
    'ph_budget': 'Бюджетті таңдаңыз',
    'field_interests': 'Қызығушылықтар',
    'ph_interests': 'мыс. Табиғат, Тарих, Тағам',
    'field_location': 'Орналасқан жері',
    'ph_location': 'мыс. Шарын шатқалы',
    'field_type': 'Орын түрі',
    'ph_type': 'Түрін таңдаңыз',
    'field_phrase': 'Не айту керек?',
    'ph_phrase': 'мыс. Бұл қанша тұрады?',
    'field_context': 'Жағдай',
    'ph_context': 'мыс. Базарда',
    'field_activity': 'Белсенділік/Орын',
    'ph_activity': 'мыс. Қысқы жорық',
    'field_trip_details': 'Сапар туралы',
    'ph_trip_details': 'мыс. Бурабайда 3 күн',

    'field_start_point': 'Басталу нүктесі',
    'ph_start_point': 'мыс. Алматы',
    'field_end_point': 'Аяқталу нүктесі',
    'ph_end_point': 'мыс. Көлсай',
    'field_transport': 'Жүру тәсілі',
    'ph_transport': 'Тәсілді таңдаңыз',
    'field_focus': 'Сапар мақсаты',
    'ph_focus': 'мыс. Ежелгі ескерткіштер',
    'field_terrain': 'Жер бедері',
    'ph_terrain': 'мыс. Тау шыңдары',
    'field_travelers': 'Жолаушылар',
    'ph_travelers': 'мыс. 2 адам',
    'field_days': 'Күндер',
    'ph_days': 'мыс. 3',
    'field_comfort': 'Жайлылық',
    'ph_comfort': 'Стильді таңдаңыз',
    
    'opt_budget': 'Үнемді',
    'opt_moderate': 'Орташа',
    'opt_luxury': 'Люкс',
    'opt_nomadic': 'Көшпенді',
    'opt_nature': 'Табиғат',
    'opt_culture': 'Мәдениет',
    'opt_food': 'Тағам',
    'opt_photo': 'Фото орын',
    'opt_foot': 'Жаяу',
    'opt_horse': 'Атпен',
    'opt_suv': 'Жол талғамайтын көлік',
    'opt_bike': 'Велосипед',
    'opt_tent': 'Шатыр',
    'opt_yurt': 'Киіз үй',
    'opt_guesthouse': 'Қонақ үй',
    'opt_ascetic': 'Тақуа',
    'opt_sultan': 'Сұлтан',

    'ai_listening': 'Желді тыңдау...',
    'ai_ways_land': 'Жер жолдары',
    'ai_consulting': 'Аруақтармен кеңесу...',
    'ai_new_search': 'Жаңа іздеу',
    'ai_invoke': 'Даналықты шақыру',
    'ai_ready': 'Шақыруға дайын',
    'ai_nature_breath': 'Табиғат тынысы',
    'ai_sky_clarity': 'Аспан мөлдірлігі',
    'ai_earth_essence': 'Жер нәрі',
    'ai_traveler': 'Жолаушы',
    'ai_curator': 'Шырақшы',
    'ai_speak_placeholder': 'Даламен тілдесу...',
    'ai_morning': 'Таң',
    'ai_afternoon': 'Түс',
    'ai_evening': 'Кеш',
    'ai_tips': 'Шырақшы кеңестері',
    'aspan_intel': 'Аспан Интел',
    'nomad_pack': 'Жолаушы Қоржыны',
    'steppe_realist': 'Дала Реалисі',
    'ethos_guide': 'Этос Нұсқаулығы',
    'star_nav': 'Жұлдызшы',
    'ghost_protocol': 'Елес Хаттамасы',
    'starnav_protocol': 'Жұлдызшы Хаттамасы',
    'consult_ancestors': 'Аруақтармен кеңесу',
    'celestial_guide': 'Аспан Нұсқаушысы',
    'return_nav': 'Навигацияға оралу',
    'bearing': 'Бағыт',
    'latitude': 'Ендік',
    'longitude': 'Бойлық',
    'searching': 'Іздеу...',
    'signal_interrupted': 'Сигнал үзілді',
    'force_calibration': 'Күшпен реттеу',
    'reading_sky': 'Аспанды оқу...',
    'clouds_obscure': 'Бұлттар аспанды жапты',
    'ancestors_silent': 'Аруақтар үнсіз. Әзірше ішкі түйсігіңізге сеніңіз.',

    'aspan_intelligence': 'Aspan Intelligence',
    'weather_logistics': 'Ауа райы және Логистика',
    'interrogating_spirits': 'Аспан Рухтарымен байланыс...',
    'strategic_difficulty': 'Стратегиялық Қиындық',
    'temperature': 'Температура',
    'feels_like': 'Сезіледі',
    'wind_velocity': 'Жел Жылдамдығы',
    'direction': 'Бағыты',
    'humidity': 'Ылғалдылық',
    'precip_potential': 'Жауын-шашын ықтималдығы',
    'pressure': 'Қысым',
    'provider': 'Дереккөз',
    'emergency_comms': 'Шұғыл Байланыс',
    'steppe_warning': 'Дала рухты сынайды. Егер деңгей ҚЫЗЫЛ болса, P-4 және A-2 трассаларынан аулақ болыңыз. Эвакуация үшін 112 хабарласыңыз.',
    'signal_interference': 'Сигнал Бөгелісі',
    'satellite_lost': 'Спутник байланысы үзілді',

    'loadout_balancer': 'Жүк Балансы',
    'survival_inventory': 'Тіршілік Қоржыны',
    'current_payload': 'Ағымдағы Салмақ',
    'nomadic_limit': 'Көшпенді Шектеуі',
    'transport_calc': 'Ат, түйе немесе жол талғамайтын көлік үшін есептелген.',
    'scan_item': 'Қоржынға зат қосу...',
    'deconstruct_arsenal': 'Арсеналды таратасыз ба?',
    'cat_global': 'Негізгі',
    'cat_almaty': 'Тау',
    'cat_mangystau': 'Шөл',
    'cat_astana': 'Дала/Жел',
    'cat_etiquette': 'Әдеп',
    'item_sat_phone': 'Спутниктік телефон',
    'item_solar': 'Күн батареясы',
    'item_first_aid': 'Алғашқы көмек',
    'item_adapter': 'Адаптер',
    'item_boots': 'Треккинг аяқ киімі',
    'item_sunscreen': 'Күннен қорғаныс',
    'item_jacket': 'Тау күртешесі',
    'item_water': 'Су қоры (10л)',
    'item_goggles': 'Құм көзілдірігі',
    'item_shemagh': 'Шемаг (Орамал)',
    'item_windbreaker': 'Желбегей',
    'item_thermal': 'Термоішкікиім',
    'item_lip_balm': 'Ерін бальзамы',
    'item_socks': 'Таза шұлық',
    'item_gifts': 'Сыйлықтар (Шашу)',
    'item_headscarf': 'Орамал',

    'steppe_realist_ai': 'Дала Реалисі AI',
    'time_distortion': 'Логистика және Уақыт',
    'point_a': 'А Нүктесі (Басы)',
    'point_b': 'Б Нүктесі (Соңы)',
    'calc_trajectory': 'Траекторияны Есептеу',
    'consulting_spirits': 'Ұлы Рухтармен Кеңесу...',
    'nomad_reality_check': 'Шынайылықты Тексеру',
    'distortion': 'Бұрмалау',
    'geo_scale': 'Масштаб',
    'calc_distance': 'Қашықтық',
    'air_bridge': 'Әуе Көпірі',
    'nomad_rail': 'Темір Жол',
    'overland_drive': 'Көлікпен',
    'sync_steppe': 'Даламен Синхрондау...',

    'ethos_guide_title': 'Этос Нұсқаулығы',
    'unwritten_code': 'Даланың Жазылмаған Заңы',
    'tab_lexicon': 'Лексикон',
    'tab_etiquette': 'Әдеп',
    'tab_blessings': 'Бата',
    'tab_oracle': 'Оракул',
    'literal': 'Мағынасы',
    'resp': 'Жауап',
    'elder_freq': 'Ақсақал Жиілігі',
    'activate_trans': 'Таратуды Бастау',
    'bata_desc': 'Астың соңында айтылатын бата. Үйге құт-береке шақырады.',
    'wisdom_test': 'Даналық Сынағы',
    'level': 'деңгей',

    'steppe_guard': 'Дала Сақшысы',
    'pdf_desc': 'Байланыс жоқ жерлер үшін маршрутты PDF форматқа жүктеңіз.',
    'enter_region': 'АЙМАҚТЫ ЕНГІЗІҢІЗ',
    'download_protocol': 'ХАТТАМАНЫ ЖҮКТЕУ',
    'generating': 'ДАЙЫНДАЛУДА...',
    'pdf_footer': 'Бұл құжатта карталар мен шұғыл нөмірлер бар. Сапар алдында сақтап алыңыз.',
    'nomad_identity': 'Цифрлық Көшпенді Келбеті',
    'level_explorer': '1-деңгейлі Зерттеуші',
    'next_chapter_section': 'Келесі Тарау',
    'empty_state_planner': 'Дала күтіп тұр. Алғашқы бағытыңызды құрыңыз.',
    'empty_reel': 'Бос Таспа',
    'passport_id': 'Төлқұжат / ID',
    'emergency_contact_label': 'Шұғыл Байланыс',
    'syncing': 'Синхрондау...',
    'update_identity': 'Деректерді Жаңарту',
    'sign_out': 'Шығу',
    'local_time': 'Жергілікті Уақыт',
    'planning_status': 'Жоспарлау',
    'confirmed_status': 'Расталды',
    'upcoming_label': 'Күтілуде',
    'create_first_route': 'Алғашқы бағытты құру',
    'phone_label': 'Телефон нөмірі',

    'places_index': 'Индекс 02',
    'places_database': 'Орындар дерекқоры',
    'places_header': 'Киелі жерлер',
    'places_all': 'Барлық аймақтар',
    'places_mountains': 'Таулар',
    'places_lakes': 'Көлдер',
    'places_forests': 'Ормандар',
    'places_deserts': 'Шөлдер',
    'places_found': 'орын табылды',
    'places_view_details': 'Толығырақ көру',
    'places_description': 'Сипаттамасы',
    'places_altitude': 'Биіктігі',
    'places_difficulty': 'Қиындығы',
    'places_distance': 'Қашықтық',
    'places_time': 'Уақыт',
    'places_season': 'Маусым',
    'places_accommodation': 'Жатын орын',
    'places_add_to_trip': 'Сапарға қосу',
    'places_share': 'Бөлісу',
    'places_view_map': 'Картадан көру',
    'saved': 'Сақталды',
    'save_to_collection': 'Жинаққа қосу',
    'link_copied': 'Сілтеме көшірілді',

    'regions_north': 'Солтүстік',
    'regions_south': 'Оңтүстік',
    'regions_west': 'Батыс',
    'regions_east': 'Шығыс',
    'regions_north_title': 'Зүбаржат ормандар',
    'regions_south_title': 'Көне шыңдар',
    'regions_west_title': 'Киелі шөл',
    'regions_east_title': 'Мистикалық Алтай',
    'regions_north_desc': 'Даланың тынысы. Қарағайлы ормандар, мөлдір көлдер мен аңыздар.',
    'regions_south_desc': 'Өркениет бесігі. Жібек жолы бойындағы қалалар мен заңғар таулар.',
    'regions_west_desc': 'Мұхит пен шаңның түйіскен жері. Жерасты мешіттері мен ақ каньондар.',
    'regions_east_desc': 'Бақсылар мекені. Қалың тайга, бал және аюдың киесі.',
    'regions_temperature': 'Температура',
    'regions_wind': 'Жел',
    'regions_humidity': 'Ылғалдылық',
    'regions_high': 'Жоғары',
    'regions_low': 'Төмен',
    'regions_medium': 'Орташа',
    'regions_expedition_sites': 'Экспедиция нысандары',
    'regions_open_on_map': 'Картадан ашу',

    'tours_index': 'Индекс 003',
    'tours_expeditions': 'Экспедициялар',
    'tours_great_steppe_spirit': 'Ұлы Дала Рухы',
    'tours_tagline': 'Көшпенділер ізімен жүріп өтіңіз. Тарих, табиғат және болашақ тоғысқан жерде.',
    'tours_all': 'Барлығы',
    'tours_north': 'Солтүстік',
    'tours_south': 'Оңтүстік',
    'tours_west': 'Батыс',
    'tours_east': 'Шығыс',
    'tours_central': 'Орталық',
    'tours_search': 'ІЗДЕУ...',
    'tours_view': 'Көру',
    'tours_type_cultural': 'Мәдени',
    'tours_type_adventure': 'Шытырман',
    'tours_type_offroad': 'Офф-роуд',
    'tours_type_nature': 'Табиғат',
    'tours_type_scientific': 'Ғылыми',
    'tours_type_historical': 'Тарихи',
    'tours_type_healing': 'Сауықтыру',
    'tours_type_hobby': 'Хобби',
    'tours_type_extreme': 'Экстремалды',
    'tours_difficulty_easy': 'Жеңіл',
    'tours_difficulty_medium': 'Орташа',
    'tours_difficulty_hard': 'Қиын',
    'tours_difficulty_extreme': 'Экстремалды',
    'tours_days': 'күн',
    'tours_itinerary': 'Маршрут',
    'tours_day': 'Күн',
    'tours_included': 'Қамтылған',
    'tours_what_to_bring': 'Не алып жүру керек',
    'tours_book_now': 'Қазір брондау',
    'tours_close': 'Жабу',
    'tours_reserve': 'Саяхатқа жазылу',
    'tours_itinerary_title': 'Саяхат бағдарламасы',
    'tours_included_title': 'Қамтылған қызметтер',
    'tours_gear_title': 'Қажетті жабдықтар',
    'tours_booking_info': 'Брондау және байланыс',
    'tours_talk_agent': 'Агентпен сөйлесу',
    'tours_available': 'Қолжетімді турлар',
    'tours_found': 'бағыт табылды',
    'tours_region_north': 'Солтүстік',
    'tours_region_south': 'Оңтүстік',
    'tours_region_west': 'Батыс',
    'tours_region_east': 'Шығыс',
    'tours_region_central': 'Орталық',
    'tours_region_almaty': 'Алматы',
    'tours_region_astana': 'Астана',
    'tours_diff_easy': 'Жеңіл',
    'tours_diff_medium': 'Орташа',
    'tours_diff_hard': 'Қиын',
    'tours_diff_extreme': 'Экстремалды',

    'map_tagline': 'Көшпенді футуризм: Интерактивті карта',
    'map_filters': 'Карта сүзгілері',
    'all_places_count': 'Барлық жерлер',
    'return_to_map': 'Картаға оралу',
    'connection_lost': 'Атласпен байланыс үзілді',
    'map_load_error': 'Картаны жүктеу мүмкін болмады. Интернет байланысын тексеріңіз.',
    'reload': 'Қайта жүктеу',
    'loading_map': 'Карта ашылуда...',
    'loading_config': 'Конфигурация жүктелуде...',
    'return_to_atlas': 'Атласқа оралу',
    'view_3d': '3D форматында көру',
    'street_view': 'Көше көрінісі',
    'street_view_not_found': 'Бұл жерде көше көрінісі қолжетімсіз',
    'street_view_loading': 'Көрініс жүктелуде...',
    'terrain_view': 'Бедер',
    'sacred_places': 'Киелі жерлер',
    'nature_places': 'Табиғат',
    'history_places': 'Тарих',
    'map_lat': 'Ендік',
    'map_lng': 'Бойлық',
    'geolocation_not_supported': 'Геолокация қолжетімсіз',
    'tea_title': 'Шай Мәдениеті',
    'tea_desc': 'Шайды оң қолмен алыңыз. Кесенің жартылай құйылуы (Саба) - "Мен сені сыйлаймын, ұзақ отыр" деген белгі.',
    'dastarkhan_title': 'Дастарқан',
    'dastarkhan_desc': 'Дастарқан - киелі. Оны аттауға болмайды.',
    'bread_title': 'Нан',
    'bread_desc': 'Нанды төңкеріп қоймаңыз. Қиқымын жерге тастамаңыз.',
    'yurt_title': 'Киіз үйге кіру',
    'yurt_desc': 'Оң аяқпен кіріңіз. Босағаны баспаңыз.',
    'quiz_q1': 'Кесенің жартылай құйылуы (Саба) нені білдіреді?',
    'quiz_q1_a1': 'Шай бітіп қалды',
    'quiz_q1_a2': 'Қонақтың ұзақ отырғанын қалайды',
    'quiz_q1_a3': 'Қонақтың кеткенін қалайды',
    'quiz_q2': 'Киіз үйге қай аяқпен кіру керек?',
    'quiz_q2_a1': 'Сол',
    'quiz_q2_a2': 'Оң',
    'quiz_q2_a3': 'Маңызды емес',
    'quiz_q3': 'Шашу деген не?',
    'quiz_q3_a1': 'Ат жарысы',
    'quiz_q3_a2': 'Тәтті шашу салты',
    'quiz_q3_a3': 'Бас киім',
    'quiz_q4': 'Нанды неге төңкеріп қоймайды?',
    'quiz_q4_a1': 'Қабығы бұзылады',
    'quiz_q4_a2': 'Нанның киесі бар',
    'quiz_q4_a3': 'Ауа райы бұзылады',
    'pdf_title': 'KENDALA: ЕЛЕС ХАТТАМАСЫ',
    'pdf_target': 'НЫСАН',
    'pdf_generated': 'ЖАСАЛҒАН КҮНІ',
    'pdf_season': 'МАУСЫМ',
    'pdf_temp': 'ТЕМП',
    'pdf_visual_recon': 'I. ВИЗУАЛДЫ БАРЛАУ',
    'pdf_map_unavailable': 'Карта деректері офлайн қолжетімсіз',
    'pdf_threat_assessment': 'II. ҚАУІПТІ БАҒАЛАУ',
    'pdf_primary_alert': 'БАСТЫ ЕСКЕРТУ:',
    'pdf_hazards': 'ҚАУІПТЕР:',
    'pdf_gear_check': 'III. ЖАБДЫҚТАРДЫ ТЕКСЕРУ',
    'pdf_cultural_intel': 'IV. МӘДЕНИ ИНТЕЛ',
    'pdf_emergency_frequencies': 'ШҰҒЫЛ БАЙЛАНЫС ЖИІЛІКТЕРІ',
    'pdf_police': 'ПОЛИЦИЯ / ӨРТ / ЖЕДЕЛ ЖӘРДЕМ: 112',
    'pdf_roadside': 'ЖОЛ КӨМЕГІ (ҚазАвтоЖол): 1403',
    'pdf_confidential': 'ҚҰПИЯ: KENDALA ХАТТАМАСЫМЕН ЖАСАЛҒАН. ТЕК ЖОЛ ҮШІН.',
    'proto_caution': 'Жалпы сақтық шаралары',
    'proto_check_news': 'Жергілікті жаңалықтарды тексеріңіз',
    'proto_respect': 'Жергілікті дәстүрлер мен үлкендерді сыйлаңыз.',
    'proto_water': 'Су',
    'proto_warm_clothes': 'Жылы киім',
    'proto_map': 'Карта',
    'proto_dial_112': 'Барлық төтенше жағдайлар үшін 112 нөмірін теріңіз.',

    'ui_whispers_earth': 'Дала сыбыры',
    'ui_echoes_past': 'Өткеннің жаңғырығы',
    'ui_original_breath': 'Алғашқы тыныс',
    'ui_terrain_analysis': 'Жер бедерін талдау',
    'ui_resting_sanctuaries': 'Тынығу орындары',
    'ui_path_guardian': 'Жол сақшысының ескертуі',
    'ui_total_path_weight': 'Жолдың жалпы салмағы',
    'ui_nomadic_wisdom_saving': 'Көшпенді даналығы: Үнемдеу жолы',
    'ui_traveler': 'Саяхатшы',
    'ui_curator': 'Шырақшы',
    'ui_syncing_path': 'Жолды үйлестіру...',
    'ui_update_analysis': 'Талдауды жаңарту',
    'ui_process_request': 'Сұранысты өңдеу',
    'ui_rituals': 'Рәсімдер',
    'ui_the_curator': 'Шырақшы',
    'ui_ai_guide_header': 'AI ГИД',
    'ui_thinking': 'ОЙЛАНУДА',
    'ui_secret_vision': 'Құпия көрініс',
    'ui_manifest_path': 'Жолды ашу',
    'ui_kinship_lore': 'Туыстық және аңыз',
    'ui_back': 'Артқа',
    'ai_save_to_planner': 'Жоспарлаушыға сақтау',
    'ai_add_to_trip': 'Сапарға қосу',
    'ai_trip_saved': 'Сапар жоспарлаушыға сақталды',
    'ai_open_planner': 'Жоспарлаушыны ашу',
    'ai_play_flyover': 'Рейсті ойнату',
    'ai_gem_added': 'Жасырын жауһар сапарға қосылды',
    'ai_route_saved': 'Бағыт сапарға сақталды',
    'ai_save_and_fly': 'Сақтау және ұшу',
    'ai_saved_success': 'Сәтті сақталды',
    'add_city': 'Қала қосу',
    'enter_city_name': 'Қала атауын енгізіңіз',
    'city_added': 'Қала қосылды',

    'hero_scroll': 'Зерттеу үшін төмен сырғытыңыз',
    'hero_discover': 'KENDALA АШЫҢЫЗ',
    'hero_platform_desc': 'Қазақстан бойынша премиум саяхат платформасы — AI гидпен, кинематографиялық ұшып отумен және көшпенді құралдармен.',
    'hero_feat_ai_title': 'AI Гид',
    'hero_feat_ai_desc': 'Жасанды интеллект маршрут жоспарлайды, жасырын жерлерді тауып, GPS координаттарымен толық саяхат жасайды.',
    'hero_feat_ai_tag': 'ИНТЕЛЛЕКТ',
    'hero_feat_flyover_title': 'Ұшып Оту',
    'hero_feat_flyover_desc': 'Маршрутыңыз бойынша кинематографиялық 3D ұшу — Street View панорамасымен, аялдамалармен және күндік бөлімдермен.',
    'hero_feat_flyover_tag': 'КИНЕМАТОГРАФ',
    'hero_feat_planner_title': 'Жол Жоспарлаушы',
    'hero_feat_planner_desc': 'Күн сайынғы маршрут, бюджет есептегіші, PDF экспорт және AI маршруттарын бір батырмамен сақтау.',
    'hero_feat_planner_tag': 'ҰЙЫМДАСТЫРУ',
    'hero_feat_map_title': 'Интерактивті Карта',
    'hero_feat_map_desc': '200+ киелі жер, аймақтық сүзгілер, жанды ауа-райы деректері және бір батырмамен навигация.',
    'hero_feat_map_tag': 'НАВИГАЦИЯ',
    'hero_feat_culture_title': 'Мәдени Мұра',
    'hero_feat_culture_desc': 'Көшпенді дәстүрлер, домбыра, ұлттық тағамдар, салт-дәстүрлер — интерактивті мәдениет кітапханасы.',
    'hero_feat_culture_tag': 'МҰРА',
    'hero_feat_stays_title': 'Тұрғын Үйлер',
    'hero_feat_stays_desc': 'Киіз үйлерден бутик қонақ үйлерге дейін — аймақ бойынша іріктелген орындар.',
    'hero_feat_stays_tag': 'ОРНАЛАСУ',
    'hero_feat_tools_title': 'Көшпенді Құралдар',
    'hero_feat_tools_desc': 'Ауа райы, қашықтық есептегіш, жабдық тізімі, мәдениет нұсқаулығы және PDF офлайн хаттама.',
    'hero_feat_tools_tag': 'ЖАРАҚТАР',
    'hero_cta_start': 'Саяхатты бастау',
    'hero_cta_explore': 'Мүмкіндіктерді зерттеу',
    'hero_world_awaits': 'Ұлы Дала Күтуде',
    'hero_built_for': 'Қазақстан саяхатшылары үшін жасалған',

    'flyover_title': 'KENDALA ҰШЫП ОТУ',
    'flyover_charting': 'Бағытыңыз',
    'flyover_charting_sub': 'Жоспарлануда',
    'flyover_plotting': 'Нүктелерді белгілеу',
    'flyover_stop': 'АЯЛДАМА',
    'flyover_stops': 'АЯЛДАМАЛАР',
    'flyover_day': 'КҮН',
    'flyover_paused': 'КІДІРТІЛДІ',
    'flyover_label': 'ҰШЫП ОТУ',
    'flyover_fly': 'ҰШЫРУ',
    'flyover_pause': 'КІДІРТУ',
    'flyover_resume': 'ЖАЛҒАСТЫРУ',
    'flyover_reset': 'ҚАЙТА БАСТАУ',
    'flyover_replay': 'ҚАЙТА ОЙНАТУ',
    'flyover_complete': 'АЯҚТАЛДЫ',
    'flyover_journey_mapped': 'Жол белгіленді',
    'flyover_stops_label': 'аялдама',
    'flyover_days_label': 'күн',
    'flyover_loading_maps': 'Карталар жүктелуде…',
    'flyover_street_view': 'КӨШЕ КӨРІНІСІ',
    'flyover_sv_expand': 'Кеңейту',
    'flyover_sv_minimize': 'Кішірейту',
    'flyover_sv_close': 'Көше көрінісін жабу',
    'flyover_sv_hint': 'Айналдыру үшін сүйреңіз · Жылжу үшін көрсеткілерді басыңыз',
    'flyover_explore_map': 'Картаны зерттеу үшін сүйреңіз',
    'flyover_night': 'ТҮН',
    'flyover_dawn': 'ТАҢЕРТЕҢ',
    'flyover_morning': 'ЕРТЕ',
    'flyover_midday': 'ТҮС',
    'flyover_afternoon': 'КҮНДІЗ',
    'flyover_evening': 'КЕШКЕ',

    'history_enter_era': 'Дәуірге кіру',
    'history_back_timeline': 'Уақыт сызығына оралу',
    'history_archive_protocol': 'Мұрағат хаттамасы',
    'history_archives': 'Kendala Мұрағаты',
    'history_timelines': 'Уақыт Сызығы',
    'history_scroll_drive': 'Жүріп өту үшін сырғытыңыз',
    'history_toc': 'Мазмұны',
    'history_visual_archive': 'Визуалды Мұрағат',
    'history_end_record': 'Жазба соңы',

    'planner_magic': 'Сиқыр',
    'planner_route': 'Бағыт',
    'planner_untitled': 'Атаусыз сапар',
    'planner_auto_generate': 'Маршрутты автоматты құру',
    'planner_ai_analyzing': 'Саяхат заңдылықтарын талдау...',
    'planner_ai_finding': 'Жергілікті ерекше орындарды іздеу...',
    'planner_ai_constructing': 'Жеке маршрутыңызды құру...',

    'culture_archive_label': 'Kendala мәдени мұрағаты',
    'culture_heritage_doc': 'Мұра Құжаттамасы',

    'map_loading_config': 'Карта конфигурациясы жүктелуде...',

    'authenticating': 'Аутентификация...',
    'syncing_cultural': 'Мәдени ағындарды синхрондау...',
    'back_to_timeline': 'Уақыт сызығына оралу',
    'timelines_title': 'Уақыт сызықтары',

    'lang_code': 'kz',
  },
  ru: {
    'select_language': 'Выберите язык',
    'welcome': 'Добро пожаловать в Kendala',
    'start_journey': 'Начать путешествие',
    'skip_intro': 'Пропустить',
    'next_chapter': 'Далее',
    'chapter': 'Раздел',
    'winter': 'Зима',
    'spring': 'Весна',
    'summer': 'Лето',
    'autumn': 'Осень',
    'winter_tagline': 'Зимняя сказка',
    'spring_tagline': 'Пробуждение',
    'summer_tagline': 'Солнечный край',
    'autumn_tagline': 'Золотая пора',
    'winter_desc': 'Горнолыжные курорты',
    'spring_desc': 'Цветение степи',
    'summer_desc': 'Озера и каньоны',
    'autumn_desc': 'Краски осени',
    'winter_full': 'Насладитесь тишиной и величием заснеженных гор Алатау.',
    'spring_full': 'Время, когда степь оживает и покрывается ковром цветов.',
    'summer_full': 'Идеальное время для походов на Кольсай и Чарын.',
    'autumn_full': 'Золотая осень в горах Тянь-Шаня и на Алтае.',
    'hero_brand_tagline': 'ИССЛЕДУЙ КАЗАХСТАН // НАСЛЕДИЕ КОЧЕВНИКОВ',
    'hero_main_tagline': 'Откройте для себя красоту Великой Степи',
    'discover_kz': 'Путеводитель по Казахстану',
    'system_active': 'Система активна',
    'mode': 'режим',
    'digitizing_steppe': 'Цифровая Степь',
    'tools_kit': 'Инструменты',
    'digital_tools_desc': 'Всё для современного путешественника.',
    'explore': 'Исследовать',
    'index_02_title': 'Коллекция',
    'index_02_desc': 'Подборка лучших мест для вашего путешествия.',
    'featured_location': 'Избранное место',
    'read_more': 'Подробнее',
    'local_species': 'Флора и фауна',
    'home': 'Главная',
    'places': 'Локации',
    'places_title': 'Реестр сакральных мест',
    'places_year_round': 'Круглый год',
    'regions': 'Регионы',
    'tours': 'Туры',
    'map': 'Карта',
    'ai': 'AI Гид',
    'culture': 'Культура',
    'history': 'История',
    'news': 'Новости',
    'profile': 'Профиль',
    'tools': 'Инструменты',
    'stays': 'Проживание',
    'planner': 'Планировщик',
    'guide': 'Гид',
    'login': 'Войти',
    'select_season': 'Выберите сезон',
    'coordinates': 'Координаты',
    'altitude': 'Высота',
    'difficulty': 'Сложность',
    'hard': 'Сложный',
    'medium': 'Средний',
    'easy': 'Легкий',
    'view_analysis': 'Обзор',
    'instrument_analysis': 'Об инструменте',
    'history_significance': 'Историческая справка',
    'back_to_main': 'На главную',
    'menu': 'Меню',
    'system': 'Система',
    'change_season': 'Сменить сезон',
    'ai_guide_title': 'Умный помощник',
    'ai_guide_desc': 'Персональные рекомендации для вашего маршрута.',
    'digital_map_title': 'Интерактивная карта',
    'digital_map_desc': 'Детальные маршруты и навигация.',
    'culture_lib_title': 'Культурное наследие',
    'culture_lib_desc': 'Погрузитесь в историю и традиции.',
    'expeditions': 'Экспедиции',
    'traditions': 'Традиции',
    'journal': 'Журнал',
    'weather_tab': 'Погода',
    'survival_tab': 'Безопасность',
    'reality_tab': 'Расстояния',
    'culture_tab': 'Культура',
    'offline_tab': 'Офлайн',
    'road_closure_title': 'Дорожная обстановка',
    'scanning_satellites': 'Поиск спутников...',
    'travel_difficulty': 'Сложность маршрута',
    'emergency_contacts_active': 'Экстренные службы',
    'steppe_survival_packing': 'Список снаряжения',
    'reality_check_title': 'Расчет времени',
    'add_route': 'Добавить маршрут',
    'offline_safe_trip': 'Советы по безопасности',
    'download_itinerary': 'Скачать маршрут',
    'from': 'Откуда',
    'to': 'Куда',
    'distance': 'Расстояние (км)',
    'air_travel': 'Авиа',
    'talgo_express': 'Тальго',
    'standard_train': 'Поезд',
    'hours': 'ч',
    'reset': 'Сброс',
    'field_logistics': 'Логистика',
    'device_status': 'Статус',
    'satellite_stable': 'GPS сигнал стабилен',
    'nomadic_toolkit': 'Набор путешественника',
    'nomadic_arsenal': 'Снаряжение Кочевника',
    'prep_protocol': 'Протокол Подготовки',
    'current_loadout': 'Текущая Загрузка',
    'nomad_quote': '"Кочевник без снаряжения — как степь без ветра: статичен и скоро забыт."',
    'whispering_steppe': 'Голос степи',
    'nomadic_ethos': 'Философия кочевников',
    'land_remembers': 'Память земли',
    'philosophy_quote': '"Путешествие — это единственная вещь, покупая которую, становишься богаче."',
    'our_philosophy': 'Наша философия',
    'ways_of_travel': 'Виды путешествий',
    'ways_of_travel_desc': 'Откройте для себя разнообразие Казахстана.',
    'chronos': 'Время',
    'four_acts': 'Сезонные коллекции',
    'phase': 'Фаза',
    'current': 'Сейчас',
    'sacred_landmark': 'Достопримечательность',
    'elevation_label': 'Высота',
    'difficulty_label': 'Сложность',
    'your_journey_awaits': 'Начните свое путешествие',
    'journey_quote': 'Мир ждет открытий.',
    'trip_planner_title': 'Начертание пути',
    'enter_trip_name': 'Введите название пути',
    'failed_save': 'Не удалось сохранить',
    'failed_delete': 'Не удалось удалить',
    'trip_name_placeholder': 'Новое странствие',
    'trip_unnamed': 'Безымянное',
    'save_trip': 'Сохранить',
    'saving': 'Сохранение...',
    'saved_trips': 'Сохраненные пути',
    'create_new_trip': 'Начать заново',
    'no_trips': 'Пока пусто',
    'load_trips': 'Обновить',
    'delete_trip_confirm': 'Предать этот путь забвению?',
    'trip_deleted': 'Путь стерт',
    'trip_saved': 'Путь сохранен',
    'trip_switched': 'Путь начертан',
    'new_trip_created': 'Чистый лист открыт',
    'add_day': 'Продлить путь',
    'day': 'День',
    'phase_label': 'Этап',
    'events_count': 'событий',
    'add_activity': 'Вплести событие',
    'timeline_empty': 'Временная линия чиста',
    'activity_type_travel': 'Перемещение',
    'activity_type_stay': 'Проживание',
    'activity_type_activity': 'Занятие',
    'activity_type_food': 'Трапеза',
    'activity_name': 'Суть',
    'activity_location': 'Точка',
    'activity_time': 'Миг',
    'activity_cost': 'Ценность',
    'activity_notes': 'Заметки',
    'activity_submit': 'Закрепить',
    'total_budget': 'Запас сил',
    'edit_activity': 'Изменить',
    'delete_activity': 'Удалить',
    'pending_activity_added': 'Добавлено в маршрут',
    'rating': 'Рейтинг',
    'email_label': 'Почта',
    'region': 'Регион',
    'duration': 'Длительность',
    'price': 'Цена',
    'included': 'Включено',
    'not_included': 'Не включено',
    'what_to_bring': 'Что взять с собой',
    'book_now': 'Забронировать',
    'view_details': 'Подробнее',
    'days_label': 'дней',
    'day_label': 'День',
    'select_trip': 'Выберите путешествие',
    'current_draft': 'Текущий черновик',
    'confirm': 'Подтвердить',
    'add_to_planner_desc': 'Этот тур будет добавлен начиная с {day}-го дня. Существующие планы будут автоматически сдвинуты.',

    'tool_constructor_label': 'Конструктор Путешествий',
    'tool_constructor_desc': 'Создайте полный маршрут шаг за шагом.',
    'tool_hidden_gems_label': 'Скрытые Жемчужины',
    'tool_hidden_gems_desc': 'Найдите тайные места, известные лишь местным.',
    'tool_translator_label': 'Переводчик Кочевника',
    'tool_translator_desc': 'Преодолейте языковой барьер с местными фразами.',
    'tool_horizon_label': 'Путь Горизонта',
    'tool_horizon_desc': 'Поиск древних троп и маршрутов кочевников.',
    'tool_nomad_label': 'Сумка Кочевника',
    'tool_nomad_desc': 'Найдите необходимое снаряжение для пути.',
    'tool_budget_label': 'Запас Сил',
    'tool_budget_desc': 'Оцените необходимые ресурсы для поездки.',
    
    'field_destination': 'Область / Регион',
    'ph_destination': 'напр. Алматы или Мангистауская область',
    'field_duration': 'На сколько?',
    'ph_duration': 'напр. 5 дней',
    'field_budget': 'Уровень бюджета',
    'ph_budget': 'Выберите бюджет',
    'field_interests': 'Интересы',
    'ph_interests': 'напр. Природа, История, Еда',
    'field_location': 'Местоположение',
    'ph_location': 'напр. Чарынский каньон',
    'field_type': 'Тип места',
    'ph_type': 'Выберите тип',
    'field_phrase': 'Что сказать?',
    'ph_phrase': 'напр. Сколько это стоит?',
    'field_context': 'Ситуация',
    'ph_context': 'напр. На базаре',
    'field_activity': 'Занятие/Место',
    'ph_activity': 'напр. Зимний поход',
    'field_trip_details': 'О поездке',
    'ph_trip_details': 'напр. 3 дня в Боровом',

    'field_start_point': 'Точка старта',
    'ph_start_point': 'напр. Алматы',
    'field_end_point': 'Точка финиша',
    'ph_end_point': 'напр. Кольсай',
    'field_transport': 'Способ передвижения',
    'ph_transport': 'Выберите способ',
    'field_focus': 'Цель поездки',
    'ph_focus': 'напр. Древние памятники',
    'field_terrain': 'Ландшафт',
    'ph_terrain': 'напр. Горные вершины',
    'field_travelers': 'Путешественники',
    'ph_travelers': 'напр. 2 человека',
    'field_days': 'Дни',
    'ph_days': 'напр. 3',
    'field_comfort': 'Комфорт',
    'ph_comfort': 'Выберите стиль',
    
    'opt_budget': 'Бюджетно',
    'opt_moderate': 'Средне',
    'opt_luxury': 'Люкс',
    'opt_nomadic': 'Кочевой',
    'opt_nature': 'Природа',
    'opt_culture': 'Культура',
    'opt_food': 'Еда',
    'opt_photo': 'Фото-место',
    'opt_foot': 'Пешком',
    'opt_horse': 'На конях',
    'opt_suv': 'Внедорожник',
    'opt_bike': 'Велосипед',
    'opt_tent': 'Палатка',
    'opt_yurt': 'Юрта',
    'opt_guesthouse': 'Гостевой дом',
    'opt_ascetic': 'Аскет',
    'opt_sultan': 'Султан',

    'ai_listening': 'Слушаю ветер...',
    'ai_ways_land': 'Пути земли',
    'ai_consulting': 'Советуюсь с духами...',
    'ai_new_search': 'Новый поиск',
    'ai_invoke': 'Призвать мудрость',
    'ai_ready': 'Готов к призыву',
    'ai_nature_breath': 'Дыхание природы',
    'ai_sky_clarity': 'Чистота неба',
    'ai_earth_essence': 'Суть земли',
    'ai_traveler': 'Странник',
    'ai_curator': 'Хранитель',
    'ai_speak_placeholder': 'Поговорить со степью...',
    'ai_morning': 'Утро',
    'ai_afternoon': 'День',
    'ai_evening': 'Вечер',
    'ai_tips': 'Советы Хранителя',
    'aspan_intel': 'Аспан Интел',
    'nomad_pack': 'Сумка Кочевника',
    'steppe_realist': 'Степной Реалист',
    'ethos_guide': 'Кодекс Этоса',
    'star_nav': 'Звездочет',
    'ghost_protocol': 'Призрачный Протокол',
    'starnav_protocol': 'Протокол Звездочета',
    'consult_ancestors': 'Совет предков',
    'celestial_guide': 'Небесный проводник',
    'return_nav': 'Вернуться в навигацию',
    'bearing': 'Направление',
    'latitude': 'Широта',
    'longitude': 'Долгота',
    'searching': 'Поиск...',
    'signal_interrupted': 'Сигнал прерван',
    'force_calibration': 'Принудительная калибровка',
    'reading_sky': 'Читаю небо...',
    'clouds_obscure': 'Облака закрыли небо',
    'ancestors_silent': 'Предки молчат. Положитесь на интуицию.',

    'aspan_intelligence': 'Aspan Intelligence',
    'weather_logistics': 'Погода и Логистика',
    'interrogating_spirits': 'Связь с духами неба...',
    'strategic_difficulty': 'Стратегическая сложность',
    'temperature': 'Температура',
    'feels_like': 'Ощущается',
    'wind_velocity': 'Скорость ветра',
    'direction': 'Направление',
    'humidity': 'Влажность',
    'precip_potential': 'Вероятность осадков',
    'pressure': 'Давление',
    'provider': 'Источник',
    'emergency_comms': 'Экстренная связь',
    'steppe_warning': 'Степь испытывает дух. Если уровень КРАСНЫЙ, избегайте трасс P-4 и A-2. Для эвакуации звоните 112.',
    'signal_interference': 'Помехи сигнала',
    'satellite_lost': 'Связь со спутником потеряна',

    'loadout_balancer': 'Баланс груза',
    'survival_inventory': 'Инвентарь выживания',
    'current_payload': 'Текущий вес',
    'nomadic_limit': 'Лимит кочевника',
    'transport_calc': 'Рассчитано для коня, верблюда или внедорожника.',
    'scan_item': 'Добавить предмет...',
    'deconstruct_arsenal': 'Разобрать арсенал?',
    'cat_global': 'Общее',
    'cat_almaty': 'Горы',
    'cat_mangystau': 'Пустыня',
    'cat_astana': 'Степь/Ветер',
    'cat_etiquette': 'Этикет',
    'item_sat_phone': 'Спутниковый телефон',
    'item_solar': 'Солнечная панель',
    'item_first_aid': 'Аптечка',
    'item_adapter': 'Адаптер',
    'item_boots': 'Треккинговые ботинки',
    'item_sunscreen': 'Крем от солнца',
    'item_jacket': 'Горная куртка',
    'item_water': 'Запас воды (10л)',
    'item_goggles': 'Очки от песка',
    'item_shemagh': 'Шемаг (Платок)',
    'item_windbreaker': 'Ветровка',
    'item_thermal': 'Термобелье',
    'item_lip_balm': 'Бальзам для губ',
    'item_socks': 'Чистые носки',
    'item_gifts': 'Подарки (Шашу)',
    'item_headscarf': 'Платок',

    'steppe_realist_ai': 'AI Степной Реалист',
    'time_distortion': 'Логистика и Время',
    'point_a': 'Точка А (Старт)',
    'point_b': 'Точка Б (Финиш)',
    'calc_trajectory': 'Рассчитать траекторию',
    'consulting_spirits': 'Советуюсь с духами...',
    'nomad_reality_check': 'Проверка реальностью',
    'distortion': 'Искажение',
    'geo_scale': 'Масштаб',
    'calc_distance': 'Расстояние',
    'air_bridge': 'Авиамост',
    'nomad_rail': 'Железная дорога',
    'overland_drive': 'На авто',
    'sync_steppe': 'Синхронизация со степью...',

    'ethos_guide_title': 'Кодекс Этоса',
    'unwritten_code': 'Неписаный закон степи',
    'tab_lexicon': 'Лексикон',
    'tab_etiquette': 'Этикет',
    'tab_blessings': 'Благословения',
    'tab_oracle': 'Оракул',
    'literal': 'Значение',
    'resp': 'Ответ',
    'elder_freq': 'Частота старейшин',
    'activate_trans': 'Начать передачу',
    'bata_desc': 'Благословение после еды. Призывает удачу в дом.',
    'wisdom_test': 'Испытание мудростью',
    'level': 'уровень',

    'steppe_guard': 'Страж Степи',
    'pdf_desc': 'Скачайте маршрут в PDF для зон без связи.',
    'enter_region': 'ВВЕДИТЕ РЕГИОН',
    'download_protocol': 'СКАЧАТЬ ПРОТОКОЛ',
    'generating': 'ГЕНЕРАЦИЯ...',
    'pdf_footer': 'Этот документ содержит карты и экстренные номера. Сохраните перед путем.',
    'nomad_identity': 'Цифровой облик кочевника',
    'level_explorer': 'Исследователь 1-го уровня',
    'next_chapter_section': 'Следующая глава',
    'empty_state_planner': 'Степь ждет. Начертите свой первый путь.',
    'empty_reel': 'Пустая лента',
    'passport_id': 'Паспорт / ID',
    'emergency_contact_label': 'Экстренный контакт',
    'syncing': 'Синхронизация...',
    'update_identity': 'Обновить данные',
    'sign_out': 'Выйти',
    'local_time': 'Местное время',
    'planning_status': 'Планируется',
    'confirmed_status': 'Подтверждено',
    'upcoming_label': 'Предстоит',
    'create_first_route': 'Создать первый маршрут',
    'phone_label': 'Номер телефона',

    'places_index': 'Индекс 02',
    'places_database': 'База локаций',
    'places_header': 'Священные места',
    'places_all': 'Все регионы',
    'places_mountains': 'Горы',
    'places_lakes': 'Озера',
    'places_forests': 'Леса',
    'places_deserts': 'Пустыни',
    'places_found': 'мест найдено',
    'places_view_details': 'Смотреть детали',
    'places_description': 'Описание',
    'places_altitude': 'Высота',
    'places_difficulty': 'Сложность',
    'places_distance': 'Расстояние',
    'places_time': 'Время',
    'places_season': 'Сезон',
    'places_accommodation': 'Жилье',
    'places_add_to_trip': 'Добавить в путь',
    'places_share': 'Поделиться',
    'places_view_map': 'На карте',
    'saved': 'Сохранено',
    'save_to_collection': 'В коллекцию',
    'link_copied': 'Ссылка скопирована',

    'regions_north': 'Север',
    'regions_south': 'Юг',
    'regions_west': 'Запад',
    'regions_east': 'Восток',
    'regions_north_title': 'Изумрудные леса',
    'regions_south_title': 'Древние вершины',
    'regions_west_title': 'Сакральная пустыня',
    'regions_east_title': 'Мистический Алтай',
    'regions_north_desc': 'Дыхание степи. Сосновые боры, чистые озера и легенды севера.',
    'regions_south_desc': 'Колыбель цивилизации. Города Шелкового пути и заснеженные горы.',
    'regions_west_desc': 'Где встречаются океан и пыль. Подземные мечети и белые каньоны.',
    'regions_east_desc': 'Край шаманов. Густая тайга, мед и магия Алтая.',
    'regions_temperature': 'Температура',
    'regions_wind': 'Ветер',
    'regions_humidity': 'Влажность',
    'regions_high': 'Высокая',
    'regions_low': 'Низкая',
    'regions_medium': 'Средняя',
    'regions_expedition_sites': 'Объекты экспедиции',
    'regions_open_on_map': 'Открыть на карте',

    'tours_index': 'Индекс 003',
    'tours_expeditions': 'Экспедиции',
    'tours_great_steppe_spirit': 'Дух Великой Степи',
    'tours_tagline': 'Пройдите тропами кочевников. Там, где история встречается с будущим.',
    'tours_all': 'Все',
    'tours_north': 'Север',
    'tours_south': 'Юг',
    'tours_west': 'Запад',
    'tours_east': 'Восток',
    'tours_central': 'Центр',
    'tours_search': 'ПОИСК...',
    'tours_view': 'Смотреть',
    'tours_type_cultural': 'Культурный',
    'tours_type_adventure': 'Приключенческий',
    'tours_type_offroad': 'Офф-роуд',
    'tours_type_nature': 'Природный',
    'tours_type_scientific': 'Научный',
    'tours_type_historical': 'Исторический',
    'tours_type_healing': 'Оздоровительный',
    'tours_type_hobby': 'Хобби',
    'tours_type_extreme': 'Экстремальный',
    'tours_difficulty_easy': 'Легкий',
    'tours_difficulty_medium': 'Средний',
    'tours_difficulty_hard': 'Сложный',
    'tours_difficulty_extreme': 'Экстремальный',
    'tours_days': 'дней',
    'tours_itinerary': 'Маршрут',
    'tours_day': 'День',
    'tours_included': 'Включено',
    'tours_what_to_bring': 'Что взять с собой',
    'tours_book_now': 'Забронировать',
    'tours_close': 'Закрыть',
    'tours_reserve': 'Записаться на тур',
    'tours_itinerary_title': 'Программа путешествия',
    'tours_included_title': 'Включенные услуги',
    'tours_gear_title': 'Необходимое снаряжение',
    'tours_booking_info': 'Бронирование и связь',
    'tours_talk_agent': 'Связаться с агентом',
    'tours_available': 'Доступные туры',
    'tours_found': 'маршрутов найдено',
    'tours_region_north': 'Север',
    'tours_region_south': 'Юг',
    'tours_region_west': 'Запад',
    'tours_region_east': 'Восток',
    'tours_region_central': 'Центр',
    'tours_region_almaty': 'Алматы',
    'tours_region_astana': 'Астана',
    'tours_diff_easy': 'Легко',
    'tours_diff_medium': 'Средне',
    'tours_diff_hard': 'Сложно',
    'tours_diff_extreme': 'Экстрим',

    'map_tagline': 'Кочевой футуризм: Интерактивная карта',
    'map_filters': 'Фильтры карты',
    'all_places_count': 'Все локации',
    'return_to_map': 'Вернуться к карте',
    'connection_lost': 'Связь с атласом прервана',
    'map_load_error': 'Не удалось загрузить карту. Проверьте интернет.',
    'reload': 'Обновить',
    'loading_map': 'Загрузка карты...',
    'loading_config': 'Загрузка конфигурации...',
    'return_to_atlas': 'Вернуться в атлас',
    'view_3d': 'Вид 3D',
    'street_view': 'Просмотр улиц',
    'street_view_not_found': 'Панорама недоступна',
    'street_view_loading': 'Загрузка панорамы...',
    'terrain_view': 'Рельеф',
    'sacred_places': 'Сакральные',
    'nature_places': 'Природа',
    'history_places': 'История',
    'map_lat': 'Широта',
    'map_lng': 'Долгота',
    'geolocation_not_supported': 'Геолокация недоступна',
    'tea_title': 'Культура Чая',
    'tea_desc': 'Берите пиалу правой рукой. Наливать чай наполовину — знак уважения: "сиди дольше".',
    'dastarkhan_title': 'Дастархан',
    'dastarkhan_desc': 'Дастархан священен. Через него нельзя перешагивать.',
    'bread_title': 'Хлеб',
    'bread_desc': 'Не кладите хлеб обратной стороной. Не бросайте крошки.',
    'yurt_title': 'Вход в юрту',
    'yurt_desc': 'Входите с правой ноги. Не наступайте на порог.',
    'quiz_q1': 'Что значит неполная пиала чая?',
    'quiz_q1_a1': 'Чай закончился',
    'quiz_q1_a2': 'Желание, чтобы гость остался подольше',
    'quiz_q1_a3': 'Желание, чтобы гость ушел',
    'quiz_q2': 'С какой ноги входить в юрту?',
    'quiz_q2_a1': 'С левой',
    'quiz_q2_a2': 'С правой',
    'quiz_q2_a3': 'Неважно',
    'quiz_q3': 'Что такое Шашу?',
    'quiz_q3_a1': 'Скачки',
    'quiz_q3_a2': 'Обряд осыпания сладостями',
    'quiz_q3_a3': 'Головной убор',
    'quiz_q4': 'Почему нельзя переворачивать хлеб?',
    'quiz_q4_a1': 'Испортится корочка',
    'quiz_q4_a2': 'Это неуважение к еде',
    'quiz_q4_a3': 'Испортится погода',
    'pdf_title': 'KENDALA: ПРИЗРАЧНЫЙ ПРОТОКОЛ',
    'pdf_target': 'ОБЪЕКТ',
    'pdf_generated': 'ДАТА ГЕНЕРАЦИИ',
    'pdf_season': 'СЕЗОН',
    'pdf_temp': 'ТЕМП',
    'pdf_visual_recon': 'I. ВИЗУАЛЬНАЯ РАЗВЕДКА',
    'pdf_map_unavailable': 'Карта недоступна офлайн',
    'pdf_threat_assessment': 'II. ОЦЕНКА УГРОЗ',
    'pdf_primary_alert': 'ГЛАВНОЕ ПРЕДУПРЕЖДЕНИЕ:',
    'pdf_hazards': 'РИСКИ:',
    'pdf_gear_check': 'III. ПРОВЕРКА СНАРЯЖЕНИЯ',
    'pdf_cultural_intel': 'IV. КУЛЬТУРНЫЙ ИНТЕЛ',
    'pdf_emergency_frequencies': 'ЧАСТОТЫ ЭКСТРЕННОЙ СВЯЗИ',
    'pdf_police': 'ПОЛИЦИЯ / МЧС / СКОРАЯ: 112',
    'pdf_roadside': 'ПОМОЩЬ НА ДОРОГАХ (КазАвтоЖол): 1403',
    'pdf_confidential': 'КОНФИДЕНЦИАЛЬНО: СГЕНЕРИРОВАНО KENDALA. ТОЛЬКО ДЛЯ ВЫЖИВАНИЯ.',
    'proto_caution': 'Общая осторожность',
    'proto_check_news': 'Проверьте местные новости',
    'proto_respect': 'Уважайте местные традиции и старейшин.',
    'proto_water': 'Вода',
    'proto_warm_clothes': 'Теплая одежда',
    'proto_map': 'Карта',
    'proto_dial_112': 'Для всех экстренных случаев звоните 112.',

    'ui_whispers_earth': 'Шепот земли',
    'ui_echoes_past': 'Эхо прошлого',
    'ui_original_breath': 'Первозданное дыхание',
    'ui_terrain_analysis': 'Анализ ландшафта',
    'ui_resting_sanctuaries': 'Места отдыха',
    'ui_path_guardian': 'Предупреждение стража пути',
    'ui_total_path_weight': 'Общий вес пути',
    'ui_nomadic_wisdom_saving': 'Мудрость кочевника: Путь экономии',
    'ui_traveler': 'Путешественник',
    'ui_curator': 'Хранитель',
    'ui_syncing_path': 'Синхронизация пути...',
    'ui_update_analysis': 'Обновить анализ',
    'ui_process_request': 'Обработать запрос',
    'ui_rituals': 'Ритуалы',
    'ui_the_curator': 'Хранитель',
    'ui_ai_guide_header': 'AI ГИД',
    'ui_thinking': 'ДУМАЮ',
    'ui_secret_vision': 'Тайное видение',
    'ui_manifest_path': 'Проявить путь',
    'ui_kinship_lore': 'Родство и легенды',
    'ui_back': 'Назад',
    'ai_save_to_planner': 'Сохранить в планер',
    'ai_add_to_trip': 'Добавить в маршрут',
    'ai_trip_saved': 'Маршрут сохранён в планер',
    'ai_open_planner': 'Открыть планер',
    'ai_play_flyover': 'Запустить облёт',
    'ai_gem_added': 'Точка добавлена в маршрут',
    'ai_route_saved': 'Маршрут сохранён',
    'ai_save_and_fly': 'Сохранить и лететь',
    'ai_saved_success': 'Успешно сохранено',
    'add_city': 'Добавить город',
    'enter_city_name': 'Введите название города',
    'city_added': 'Город добавлен',

    'hero_scroll': 'Листайте для знакомства',
    'hero_discover': 'ОТКРОЙТЕ KENDALA',
    'hero_platform_desc': 'Премиальная travel-платформа по Казахстану — с AI-гидом, кинематографическим облётом и набором кочевника.',
    'hero_feat_ai_title': 'AI Гид',
    'hero_feat_ai_desc': 'Искусственный интеллект строит маршруты, находит скрытые жемчужины и создаёт полные путешествия с GPS-координатами.',
    'hero_feat_ai_tag': 'ИНТЕЛЛЕКТ',
    'hero_feat_flyover_title': 'Облёт Маршрута',
    'hero_feat_flyover_desc': 'Кинематографический 3D-полёт вдоль маршрута — с панорамами Street View, остановками и дневными разделами.',
    'hero_feat_flyover_tag': 'КИНЕМАТОГРАФ',
    'hero_feat_planner_title': 'Планировщик',
    'hero_feat_planner_desc': 'Подневный маршрут, расчёт бюджета, PDF-экспорт и сохранение AI-маршрутов в один клик.',
    'hero_feat_planner_tag': 'ОРГАНИЗАЦИЯ',
    'hero_feat_map_title': 'Интерактивная Карта',
    'hero_feat_map_desc': '200+ священных мест, региональные фильтры, живые данные о погоде и навигация одним кликом.',
    'hero_feat_map_tag': 'НАВИГАЦИЯ',
    'hero_feat_culture_title': 'Культурное Наследие',
    'hero_feat_culture_desc': 'Кочевые традиции, домбра, национальная кухня, обычаи — интерактивная библиотека культуры.',
    'hero_feat_culture_tag': 'НАСЛЕДИЕ',
    'hero_feat_stays_title': 'Где Остановиться',
    'hero_feat_stays_desc': 'От юрт до бутик-отелей — курируемые варианты размещения по регионам.',
    'hero_feat_stays_tag': 'РАЗМЕЩЕНИЕ',
    'hero_feat_tools_title': 'Набор Кочевника',
    'hero_feat_tools_desc': 'Погода, калькулятор расстояний, список снаряжения, культурный гид и PDF-протокол для офлайна.',
    'hero_feat_tools_tag': 'СНАРЯЖЕНИЕ',
    'hero_cta_start': 'Начать путешествие',
    'hero_cta_explore': 'Изучить возможности',
    'hero_world_awaits': 'Великая Степь Ждёт',
    'hero_built_for': 'Создано для путешественников по Казахстану',

    'flyover_title': 'KENDALA ОБЛЁТ',
    'flyover_charting': 'Ваш маршрут',
    'flyover_charting_sub': 'Прокладывается',
    'flyover_plotting': 'Нанесение точек',
    'flyover_stop': 'ОСТАНОВКА',
    'flyover_stops': 'ОСТАНОВКИ',
    'flyover_day': 'ДЕНЬ',
    'flyover_paused': 'ПАУЗА',
    'flyover_label': 'ОБЛЁТ',
    'flyover_fly': 'ЛЕТЕТЬ',
    'flyover_pause': 'ПАУЗА',
    'flyover_resume': 'ПРОДОЛЖИТЬ',
    'flyover_reset': 'СБРОС',
    'flyover_replay': 'ПОВТОРИТЬ',
    'flyover_complete': 'ЗАВЕРШЕНО',
    'flyover_journey_mapped': 'Маршрут нанесён',
    'flyover_stops_label': 'остановок',
    'flyover_days_label': 'дней',
    'flyover_loading_maps': 'Загрузка карт…',
    'flyover_street_view': 'ПАНОРАМА',
    'flyover_sv_expand': 'Развернуть',
    'flyover_sv_minimize': 'Свернуть',
    'flyover_sv_close': 'Закрыть панораму',
    'flyover_sv_hint': 'Перетащите для обзора · Нажмите стрелки для перемещения',
    'flyover_explore_map': 'Перетащите для изучения карты',
    'flyover_night': 'НОЧЬ',
    'flyover_dawn': 'РАССВЕТ',
    'flyover_morning': 'УТРО',
    'flyover_midday': 'ПОЛДЕНЬ',
    'flyover_afternoon': 'ДЕНЬ',
    'flyover_evening': 'ВЕЧЕР',

    'history_enter_era': 'Войти в эпоху',
    'history_back_timeline': 'К хронологии',
    'history_archive_protocol': 'Архивный протокол',
    'history_archives': 'Архив Kendala',
    'history_timelines': 'Хронология',
    'history_scroll_drive': 'Прокрутите для навигации',
    'history_toc': 'Содержание',
    'history_visual_archive': 'Визуальный архив',
    'history_end_record': 'Конец записи',

    'planner_magic': 'Магия',
    'planner_route': 'Маршрут',
    'planner_untitled': 'Без названия',
    'planner_auto_generate': 'Автоматическая генерация маршрута',
    'planner_ai_analyzing': 'Анализ маршрутов путешествий...',
    'planner_ai_finding': 'Поиск лучших местных впечатлений...',
    'planner_ai_constructing': 'Составление персонального маршрута...',

    'culture_archive_label': 'Культурный архив Kendala',
    'culture_heritage_doc': 'Документация наследия',

    'map_loading_config': 'Загрузка конфигурации карты...',

    'authenticating': 'Аутентификация...',
    'syncing_cultural': 'Синхронизация культурных потоков...',
    'back_to_timeline': 'Вернуться к временной шкале',
    'timelines_title': 'Временные шкалы',

    'lang_code': 'ru',
  },
  en: {
    'select_language': 'Select Language',
    'welcome': 'Welcome to Kendala',
    'start_journey': 'Start Journey',
    'skip_intro': 'Skip Intro',
    'next_chapter': 'Next Chapter',
    'chapter': 'Chapter',
    'winter': 'Winter',
    'spring': 'Spring',
    'summer': 'Summer',
    'autumn': 'Autumn',
    'winter_tagline': 'Sanctuary of Silence',
    'spring_tagline': 'Origin of Life',
    'summer_tagline': 'Solar Flare',
    'autumn_tagline': 'Golden Hour',
    'winter_desc': 'Peaks of Alatau',
    'spring_desc': 'Green Steppe',
    'summer_desc': 'Crystal Lakes',
    'autumn_desc': 'Amber Forests',
    'winter_full': 'Ski resorts and the tranquility of nature.',
    'spring_full': 'Steppe in bloom and the awakening of nature.',
    'summer_full': 'The beauty of Kolsay and Kaindy lakes.',
    'autumn_full': 'Golden colors of Altai and Tien-Shan forests.',
    'hero_brand_tagline': 'EXPLORE KAZAKHSTAN // NOMADIC HERITAGE',
    'hero_main_tagline': 'Unveil the beauty of the Great Steppe',
    'discover_kz': 'Discover Kazakhstan',
    'system_active': 'System Active',
    'mode': 'mode',
    'digitizing_steppe': 'Digitizing Steppe',
    'tools_kit': 'Tools Kit',
    'digital_tools_desc': 'Essentials for the modern nomad.',
    'explore': 'Explore',
    'index_02_title': 'Collection',
    'index_02_desc': 'A curated vision of true nature.',
    'featured_location': 'Featured Location',
    'read_more': 'Read More',
    'local_species': 'Local Fauna',
    'home': 'Home',
    'places': 'Places',
    'places_title': 'Sacred Places Registry',
    'places_year_round': 'Year Round',
    'regions': 'Regions',
    'tours': 'Tours',
    'map': 'Map',
    'ai': 'AI Guide',
    'culture': 'Culture',
    'history': 'History',
    'news': 'News',
    'profile': 'Profile',
    'tools': 'Tools',
    'stays': 'Stays',
    'planner': 'Planner',
    'guide': 'Guide',
    'login': 'Login',
    'select_season': 'Select Season',
    'coordinates': 'Coordinates',
    'altitude': 'Altitude',
    'difficulty': 'Difficulty',
    'hard': 'Hard',
    'medium': 'Medium',
    'easy': 'Easy',
    'view_analysis': 'Analysis',
    'instrument_analysis': 'About Instrument',
    'history_significance': 'Historical Significance',
    'back_to_main': 'Back to Main',
    'menu': 'Menu',
    'system': 'System',
    'change_season': 'Change Season',
    'ai_guide_title': 'Smart Assistant',
    'ai_guide_desc': 'Personal recommendations for your journey.',
    'digital_map_title': 'Interactive Map',
    'digital_map_desc': 'Detailed routes and navigation.',
    'culture_lib_title': 'Cultural Heritage',
    'culture_lib_desc': 'Dive into history and traditions.',
    'expeditions': 'Expeditions',
    'traditions': 'Traditions',
    'journal': 'Journal',
    'weather_tab': 'Weather',
    'survival_tab': 'Survival',
    'reality_tab': 'Reality',
    'culture_tab': 'Culture',
    'offline_tab': 'Offline',
    'road_closure_title': 'Road Status',
    'scanning_satellites': 'Scanning Satellites...',
    'travel_difficulty': 'Travel Difficulty',
    'emergency_contacts_active': 'Emergency Contacts',
    'steppe_survival_packing': 'Packing List',
    'reality_check_title': 'Reality Check',
    'add_route': 'Add Route',
    'offline_safe_trip': 'Safety Protocols',
    'download_itinerary': 'Download Itinerary',
    'from': 'From',
    'to': 'To',
    'distance': 'Distance (km)',
    'air_travel': 'Air Travel',
    'talgo_express': 'Talgo Express',
    'standard_train': 'Standard Train',
    'hours': 'hrs',
    'reset': 'Reset',
    'field_logistics': 'Logistics',
    'device_status': 'Device Status',
    'satellite_stable': 'GPS Stable',
    'nomadic_toolkit': 'Nomadic Toolkit',
    'nomadic_arsenal': 'Nomadic Arsenal',
    'prep_protocol': 'Prep Protocol',
    'current_loadout': 'Current Loadout',
    'nomad_quote': '"A nomad without tools is like the steppe without wind: stagnant and forgotten."',
    'whispering_steppe': 'Whispering Steppe',
    'nomadic_ethos': 'Nomadic Ethos',
    'land_remembers': 'The Land Remembers',
    'philosophy_quote': '"The journey is the only thing you buy that makes you richer."',
    'our_philosophy': 'Our Philosophy',
    'ways_of_travel': 'Ways of Travel',
    'ways_of_travel_desc': 'Discover the diverse ways to explore Kazakhstan.',
    'chronos': 'Chronos',
    'four_acts': 'Four Acts',
    'phase': 'Phase',
    'current': 'Current',
    'sacred_landmark': 'Sacred Landmark',
    'elevation_label': 'Elevation',
    'difficulty_label': 'Difficulty',
    'your_journey_awaits': 'Your Journey Awaits',
    'journey_quote': 'Every journey is a new story.',
    'trip_planner_title': 'Trip Planner',
    'enter_trip_name': 'Enter trip name',
    'failed_save': 'Failed to save',
    'failed_delete': 'Failed to delete',
    'trip_name_placeholder': 'New Trip',
    'trip_unnamed': 'Unnamed',
    'save_trip': 'Save',
    'saving': 'Saving...',
    'saved_trips': 'Saved Trips',
    'create_new_trip': 'Create New',
    'no_trips': 'No trips yet',
    'load_trips': 'Load Trips',
    'delete_trip_confirm': 'Delete this trip?',
    'trip_deleted': 'Trip deleted',
    'trip_saved': 'Trip saved',
    'trip_switched': 'Trip switched',
    'new_trip_created': 'New trip created',
    'add_day': 'Add Day',
    'day': 'Day',
    'phase_label': 'Phase',
    'events_count': 'events',
    'add_activity': 'Add Activity',
    'timeline_empty': 'Timeline empty',
    'activity_type_travel': 'Travel',
    'activity_type_stay': 'Stay',
    'activity_type_activity': 'Activity',
    'activity_type_food': 'Food',
    'activity_name': 'Name',
    'activity_location': 'Location',
    'activity_time': 'Time',
    'activity_cost': 'Cost',
    'activity_notes': 'Notes',
    'activity_submit': 'Submit',
    'total_budget': 'Total Budget',
    'edit_activity': 'Edit',
    'delete_activity': 'Delete',
    'pending_activity_added': 'Added to itinerary',
    'rating': 'Rating',
    'email_label': 'Email',
    'region': 'Region',
    'duration': 'Duration',
    'price': 'Price',
    'included': 'Included',
    'not_included': 'Not Included',
    'what_to_bring': 'What to bring',
    'book_now': 'Book Now',
    'view_details': 'View Details',
    'days_label': 'days',
    'day_label': 'Day',
    'select_trip': 'Select Trip',
    'current_draft': 'Current Draft',
    'confirm': 'Confirm',
    'add_to_planner_desc': 'This tour will be added starting from Day {day}. Existing plans will shift automatically.',

    'tool_constructor_label': 'Trip Constructor',
    'tool_constructor_desc': 'Build a complete itinerary step-by-step.',
    'tool_hidden_gems_label': 'Hidden Gems',
    'tool_hidden_gems_desc': 'Find secret spots known only to locals.',
    'tool_translator_label': 'Nomad Translator',
    'tool_translator_desc': 'Bridge the language gap with local phrases.',
    'tool_horizon_label': 'Horizon Path',
    'tool_horizon_desc': 'Search for ancient trails and nomadic routes.',
    'tool_nomad_label': 'Nomad Pack',
    'tool_nomad_desc': 'Find essential gear for the road ahead.',
    'tool_budget_label': 'Trip Budget',
    'tool_budget_desc': 'Estimate resources needed for the journey.',
    
    'field_destination': 'Region / Area',
    'ph_destination': 'e.g. Almaty or Mangystau',
    'field_duration': 'Duration',
    'ph_duration': 'e.g. 5 days',
    'field_budget': 'Budget Level',
    'ph_budget': 'Select budget',
    'field_interests': 'Interests',
    'ph_interests': 'e.g. Nature, History, Food',
    'field_location': 'Location',
    'ph_location': 'e.g. Charyn Canyon',
    'field_type': 'Place Type',
    'ph_type': 'Select type',
    'field_phrase': 'What to say?',
    'ph_phrase': 'e.g. How much is this?',
    'field_context': 'Context',
    'ph_context': 'e.g. At the bazaar',
    'field_activity': 'Activity/Place',
    'ph_activity': 'e.g. Winter hiking',
    'field_trip_details': 'Trip Details',
    'ph_trip_details': 'e.g. 3 days in Burabay',

    'field_start_point': 'Start Point',
    'ph_start_point': 'e.g. Almaty',
    'field_end_point': 'End Point',
    'ph_end_point': 'e.g. Kolsay',
    'field_transport': 'Transport Mode',
    'ph_transport': 'Select mode',
    'field_focus': 'Trip Focus',
    'ph_focus': 'e.g. Ancient monuments',
    'field_terrain': 'Terrain',
    'ph_terrain': 'e.g. Mountain peaks',
    'field_travelers': 'Travelers',
    'ph_travelers': 'e.g. 2 people',
    'field_days': 'Days',
    'ph_days': 'e.g. 3',
    'field_comfort': 'Comfort',
    'ph_comfort': 'Select style',
    
    'opt_budget': 'Budget',
    'opt_moderate': 'Moderate',
    'opt_luxury': 'Luxury',
    'opt_nomadic': 'Nomadic',
    'opt_nature': 'Nature',
    'opt_culture': 'Culture',
    'opt_food': 'Food',
    'opt_photo': 'Photo Spot',
    'opt_foot': 'On Foot',
    'opt_horse': 'Horseback',
    'opt_suv': 'SUV / Jeep',
    'opt_bike': 'Bicycle',
    'opt_tent': 'Tent',
    'opt_yurt': 'Yurt',
    'opt_guesthouse': 'Guesthouse',
    'opt_ascetic': 'Ascetic',
    'opt_sultan': 'Sultan',

    'ai_listening': 'Listening to the wind...',
    'ai_ways_land': 'Ways of the Land',
    'ai_consulting': 'Consulting spirits...',
    'ai_new_search': 'New Search',
    'ai_invoke': 'Invoke Wisdom',
    'ai_ready': 'Ready to Invoke',
    'ai_nature_breath': 'Nature\'s Breath',
    'ai_sky_clarity': 'Sky Clarity',
    'ai_earth_essence': 'Earth Essence',
    'ai_traveler': 'Traveler',
    'ai_curator': 'The Curator',
    'ai_speak_placeholder': 'Speak to the steppe...',
    'ai_morning': 'Morning',
    'ai_afternoon': 'Afternoon',
    'ai_evening': 'Evening',
    'ai_tips': 'Curator Tips',
    'aspan_intel': 'Aspan Intel',
    'nomad_pack': 'Nomad Pack',
    'steppe_realist': 'Steppe Realist',
    'ethos_guide': 'Ethos Guide',
    'star_nav': 'Star Nav',
    'ghost_protocol': 'Ghost Protocol',
    'starnav_protocol': 'Star-Nav Protocol',
    'consult_ancestors': 'Consult Ancestors',
    'celestial_guide': 'Celestial Guide',
    'return_nav': 'Return to Navigation',
    'bearing': 'Bearing',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'searching': 'Searching...',
    'signal_interrupted': 'Signal Interrupted',
    'force_calibration': 'Force Calibration',
    'reading_sky': 'Reading the sky...',
    'clouds_obscure': 'Clouds obscure the sky',
    'ancestors_silent': 'Ancestors are silent.',

    'aspan_intelligence': 'Aspan Intelligence',
    'weather_logistics': 'Weather & Logistics',
    'interrogating_spirits': 'Interrogating Spirits...',
    'strategic_difficulty': 'Strategic Difficulty',
    'temperature': 'Temperature',
    'feels_like': 'Feels Like',
    'wind_velocity': 'Wind Velocity',
    'direction': 'Direction',
    'humidity': 'Humidity',
    'precip_potential': 'Precipitation Potential',
    'pressure': 'Pressure',
    'provider': 'Provider',
    'emergency_comms': 'Emergency Comms',
    'steppe_warning': 'Steppe warning active.',
    'signal_interference': 'Signal Interference',
    'satellite_lost': 'Satellite Lost',

    'loadout_balancer': 'Loadout Balancer',
    'survival_inventory': 'Survival Inventory',
    'current_payload': 'Current Payload',
    'nomadic_limit': 'Nomadic Limit',
    'transport_calc': 'Calculated for horse, camel, or SUV.',
    'scan_item': 'Scan Item...',
    'deconstruct_arsenal': 'Deconstruct Arsenal?',
    'cat_global': 'Global',
    'cat_almaty': 'Mountains',
    'cat_mangystau': 'Desert',
    'cat_astana': 'Steppe',
    'cat_etiquette': 'Etiquette',
    'item_sat_phone': 'Satellite Phone',
    'item_solar': 'Solar Panel',
    'item_first_aid': 'First Aid Kit',
    'item_adapter': 'Adapter',
    'item_boots': 'Trekking Boots',
    'item_sunscreen': 'Sunscreen',
    'item_jacket': 'Mountain Jacket',
    'item_water': 'Water Reserve (10L)',
    'item_goggles': 'Sand Goggles',
    'item_shemagh': 'Shemagh',
    'item_windbreaker': 'Windbreaker',
    'item_thermal': 'Thermal Wear',
    'item_lip_balm': 'Lip Balm',
    'item_socks': 'Clean Socks',
    'item_gifts': 'Gifts (Shashu)',
    'item_headscarf': 'Headscarf',

    'steppe_realist_ai': 'Steppe Realist AI',
    'time_distortion': 'Time Distortion',
    'point_a': 'Point A',
    'point_b': 'Point B',
    'calc_trajectory': 'Calculate Trajectory',
    'consulting_spirits': 'Consulting Spirits...',
    'nomad_reality_check': 'Reality Check',
    'distortion': 'Distortion',
    'geo_scale': 'Scale',
    'calc_distance': 'Distance',
    'air_bridge': 'Air Bridge',
    'nomad_rail': 'Nomad Rail',
    'overland_drive': 'Overland Drive',
    'sync_steppe': 'Syncing Steppe...',

    'ethos_guide_title': 'Ethos Guide',
    'unwritten_code': 'Unwritten Code',
    'tab_lexicon': 'Lexicon',
    'tab_etiquette': 'Etiquette',
    'tab_blessings': 'Blessings',
    'tab_oracle': 'Oracle',
    'literal': 'Literal',
    'resp': 'Response',
    'elder_freq': 'Elder Frequency',
    'activate_trans': 'Activate Transmission',
    'bata_desc': 'Blessing given after a meal.',
    'wisdom_test': 'Wisdom Test',
    'level': 'Level',

    'steppe_guard': 'Steppe Guard',
    'pdf_desc': 'Download offline protocol.',
    'enter_region': 'ENTER REGION',
    'download_protocol': 'DOWNLOAD PROTOCOL',
    'generating': 'GENERATING...',
    'pdf_footer': 'Confidential survival document.',
    'nomad_identity': 'Nomad Identity',
    'level_explorer': 'Level 1 Explorer',
    'next_chapter_section': 'Next Chapter',
    'empty_state_planner': 'Steppe awaits.',
    'empty_reel': 'Empty Reel',
    'passport_id': 'Passport / ID',
    'emergency_contact_label': 'Emergency Contact',
    'syncing': 'Syncing...',
    'update_identity': 'Update Identity',
    'sign_out': 'Sign Out',
    'local_time': 'Local Time',
    'planning_status': 'Planning',
    'confirmed_status': 'Confirmed',
    'upcoming_label': 'Upcoming',
    'create_first_route': 'Create First Route',
    'phone_label': 'Phone Number',

    'places_index': 'INDEX 02',
    'places_database': 'Places Database',
    'places_header': 'Sacred Places',
    'places_all': 'All Regions',
    'places_mountains': 'Mountains',
    'places_lakes': 'Lakes',
    'places_forests': 'Forests',
    'places_deserts': 'Deserts',
    'places_found': 'places found',
    'places_view_details': 'View Details',
    'places_description': 'Description',
    'places_altitude': 'Altitude',
    'places_difficulty': 'Difficulty',
    'places_distance': 'Distance',
    'places_time': 'Time',
    'places_season': 'Season',
    'places_accommodation': 'Accommodation',
    'places_add_to_trip': 'Add to Trip',
    'places_share': 'Share',
    'places_view_map': 'View on Map',
    'saved': 'Saved',
    'save_to_collection': 'Save to Collection',
    'link_copied': 'Link Copied',

    'regions_north': 'North',
    'regions_south': 'South',
    'regions_west': 'West',
    'regions_east': 'East',
    'regions_north_title': 'Emerald Forests',
    'regions_south_title': 'Ancient Peaks',
    'regions_west_title': 'Sacred Desert',
    'regions_east_title': 'Mystic Altai',
    'regions_north_desc': 'The breath of the steppe.',
    'regions_south_desc': 'Cradle of civilization.',
    'regions_west_desc': 'Where ocean meets dust.',
    'regions_east_desc': 'Land of shamans.',
    'regions_temperature': 'Temperature',
    'regions_wind': 'Wind',
    'regions_humidity': 'Humidity',
    'regions_high': 'High',
    'regions_low': 'Low',
    'regions_medium': 'Medium',
    'regions_expedition_sites': 'Expedition Sites',
    'regions_open_on_map': 'Open on Map',

    'tours_index': 'Index 003',
    'tours_expeditions': 'Expeditions',
    'tours_great_steppe_spirit': 'Great Steppe Spirit',
    'tours_tagline': 'Walk the path of nomads.',
    'tours_all': 'All',
    'tours_north': 'North',
    'tours_south': 'South',
    'tours_west': 'West',
    'tours_east': 'East',
    'tours_central': 'Central',
    'tours_search': 'SEARCH...',
    'tours_view': 'View',
    'tours_type_cultural': 'Cultural',
    'tours_type_adventure': 'Adventure',
    'tours_type_offroad': 'Off-road',
    'tours_type_nature': 'Nature',
    'tours_type_scientific': 'Scientific',
    'tours_type_historical': 'Historical',
    'tours_type_healing': 'Healing',
    'tours_type_hobby': 'Hobby',
    'tours_type_extreme': 'Extreme',
    'tours_difficulty_easy': 'Easy',
    'tours_difficulty_medium': 'Medium',
    'tours_difficulty_hard': 'Hard',
    'tours_difficulty_extreme': 'Extreme',
    'tours_days': 'days',
    'tours_itinerary': 'Itinerary',
    'tours_day': 'Day',
    'tours_included': 'Included',
    'tours_what_to_bring': 'What to bring',
    'tours_book_now': 'Book Now',
    'tours_close': 'Close',
    'tours_reserve': 'Reserve Spot',
    'tours_itinerary_title': 'Itinerary',
    'tours_included_title': 'Included Services',
    'tours_gear_title': 'Required Gear',
    'tours_booking_info': 'Booking Info',
    'tours_talk_agent': 'Talk to Agent',
    'tours_available': 'Available Tours',
    'tours_found': 'tours found',
    'tours_region_north': 'North',
    'tours_region_south': 'South',
    'tours_region_west': 'West',
    'tours_region_east': 'East',
    'tours_region_central': 'Central',
    'tours_region_almaty': 'Almaty',
    'tours_region_astana': 'Astana',
    'tours_diff_easy': 'Easy',
    'tours_diff_medium': 'Medium',
    'tours_diff_hard': 'Hard',
    'tours_diff_extreme': 'Extreme',

    'map_tagline': 'Nomadic Futurism: Interactive Map',
    'map_filters': 'Map Filters',
    'all_places_count': 'All Locations',
    'return_to_map': 'Return to Map',
    'connection_lost': 'Atlas link severed',
    'map_load_error': 'Failed to load atlas. Check satellite link.',
    'reload': 'Reload',
    'loading_map': 'Loading Atlas...',
    'loading_config': 'Loading Config...',
    'return_to_atlas': 'Return to Atlas',
    'view_3d': '3D View',
    'street_view': 'Street View',
    'street_view_not_found': 'Panorama not available',
    'street_view_loading': 'Loading panorama...',
    'terrain_view': 'Terrain',
    'sacred_places': 'Sacred',
    'nature_places': 'Nature',
    'history_places': 'History',
    'map_lat': 'Lat',
    'map_lng': 'Lng',
    'geolocation_not_supported': 'Geolocation unavailable',
    'tea_title': 'Tea Culture',
    'tea_desc': 'Take the bowl with your right hand. Pouring tea halfway is a sign of respect: "stay longer".',
    'dastarkhan_title': 'Dastarkhan',
    'dastarkhan_desc': 'Dastarkhan is sacred. Never step over it.',
    'bread_title': 'Bread',
    'bread_desc': 'Never flip bread face down. Do not drop crumbs.',
    'yurt_title': 'Entering Yurt',
    'yurt_desc': 'Enter with your right foot. Do not step on the threshold.',
    'quiz_q1': 'What does a half-full cup of tea mean?',
    'quiz_q1_a1': 'Tea is finishing',
    'quiz_q1_a2': 'Desire for guest to stay longer',
    'quiz_q1_a3': 'Desire for guest to leave',
    'quiz_q2': 'Which foot to use when entering a yurt?',
    'quiz_q2_a1': 'Left',
    'quiz_q2_a2': 'Right',
    'quiz_q2_a3': 'Doesn\'t matter',
    'quiz_q3': 'What is Shashu?',
    'quiz_q3_a1': 'Horse race',
    'quiz_q3_a2': 'Ritual of scattering sweets',
    'quiz_q3_a3': 'Headwear',
    'quiz_q4': 'Why shouldn\'t you flip bread?',
    'quiz_q4_a1': 'Crust will break',
    'quiz_q4_a2': 'It is disrespectful to food',
    'quiz_q4_a3': 'Weather will change',
    'pdf_title': 'KENDALA: GHOST PROTOCOL',
    'pdf_target': 'TARGET',
    'pdf_generated': 'GENERATED ON',
    'pdf_season': 'SEASON',
    'pdf_temp': 'TEMP',
    'pdf_visual_recon': 'I. VISUAL RECON',
    'pdf_map_unavailable': 'Map data unavailable offline',
    'pdf_threat_assessment': 'II. THREAT ASSESSMENT',
    'pdf_primary_alert': 'PRIMARY ALERT:',
    'pdf_hazards': 'HAZARDS:',
    'pdf_gear_check': 'III. GEAR CHECK',
    'pdf_cultural_intel': 'IV. CULTURAL INTEL',
    'pdf_emergency_frequencies': 'EMERGENCY FREQUENCIES',
    'pdf_police': 'POLICE / FIRE / AMBULANCE: 112',
    'pdf_roadside': 'ROADSIDE ASSISTANCE (KazAutoZhol): 1403',
    'pdf_confidential': 'CONFIDENTIAL: GENERATED BY KENDALA. FOR SURVIVAL USE ONLY.',
    'proto_caution': 'General Caution Required',
    'proto_check_news': 'Check Local News',
    'proto_respect': 'Respect local traditions and elders.',
    'proto_water': 'Water',
    'proto_warm_clothes': 'Warm Clothes',
    'proto_map': 'Map',
    'proto_dial_112': 'For all emergencies dial 112.',

    'ui_whispers_earth': 'Whispers of the Earth',
    'ui_echoes_past': 'Echoes of the Past',
    'ui_original_breath': 'Original Breath',
    'ui_terrain_analysis': 'Terrain Analysis',
    'ui_resting_sanctuaries': 'Resting Sanctuaries',
    'ui_path_guardian': 'Path Guardian Warning',
    'ui_total_path_weight': 'Total Path Weight',
    'ui_nomadic_wisdom_saving': 'Nomadic Wisdom: Saving Path',
    'ui_traveler': 'Traveler',
    'ui_curator': 'Curator',
    'ui_syncing_path': 'Syncing Path...',
    'ui_update_analysis': 'Update Analysis',
    'ui_process_request': 'Process Request',
    'ui_rituals': 'Rituals',
    'ui_the_curator': 'The Curator',
    'ui_ai_guide_header': 'AI GUIDE',
    'ui_thinking': 'THINKING',
    'ui_secret_vision': 'Secret Vision',
    'ui_manifest_path': 'Manifest Path',
    'ui_kinship_lore': 'Kinship & Lore',
    'ui_back': 'Back',
    'ai_save_to_planner': 'Save to Planner',
    'ai_add_to_trip': 'Add to Trip',
    'ai_trip_saved': 'Trip saved to planner',
    'ai_open_planner': 'Open Planner',
    'ai_play_flyover': 'Play Flyover',
    'ai_gem_added': 'Gem added to trip',
    'ai_route_saved': 'Route saved to trip',
    'ai_save_and_fly': 'Save & Fly',
    'ai_saved_success': 'Successfully saved',
    'add_city': 'Add City',
    'enter_city_name': 'Enter city name',
    'city_added': 'City added',

    'hero_scroll': 'Scroll to discover',
    'hero_discover': 'DISCOVER KENDALA',
    'hero_platform_desc': 'A premium travel platform for Kazakhstan — powered by an AI guide, cinematic flyovers, and a nomadic toolkit.',
    'hero_feat_ai_title': 'AI Guide',
    'hero_feat_ai_desc': 'Artificial intelligence crafts routes, discovers hidden gems, and builds full itineraries with GPS coordinates.',
    'hero_feat_ai_tag': 'INTELLIGENCE',
    'hero_feat_flyover_title': 'Route Flyover',
    'hero_feat_flyover_desc': 'A cinematic 3D flight along your route — with Street View panoramas, stop cards, and day-by-day chapters.',
    'hero_feat_flyover_tag': 'CINEMATIC',
    'hero_feat_planner_title': 'Trip Planner',
    'hero_feat_planner_desc': 'Day-by-day itinerary, budget calculator, PDF export, and one-click save of AI-generated routes.',
    'hero_feat_planner_tag': 'ORGANIZE',
    'hero_feat_map_title': 'Interactive Map',
    'hero_feat_map_desc': '200+ sacred places, regional filters, live weather data, and one-click navigation.',
    'hero_feat_map_tag': 'NAVIGATE',
    'hero_feat_culture_title': 'Cultural Heritage',
    'hero_feat_culture_desc': 'Nomadic traditions, dombra, national cuisine, customs — an interactive cultural library.',
    'hero_feat_culture_tag': 'HERITAGE',
    'hero_feat_stays_title': 'Where to Stay',
    'hero_feat_stays_desc': 'From yurts to boutique hotels — curated accommodation options by region.',
    'hero_feat_stays_tag': 'ACCOMMODATION',
    'hero_feat_tools_title': 'Nomad Toolkit',
    'hero_feat_tools_desc': 'Weather, distance calculator, packing list, culture guide, and an offline PDF protocol.',
    'hero_feat_tools_tag': 'GEAR',
    'hero_cta_start': 'Begin Your Journey',
    'hero_cta_explore': 'Explore Features',
    'hero_world_awaits': 'The Great Steppe Awaits',
    'hero_built_for': 'Built for travelers exploring Kazakhstan',

    'flyover_title': 'KENDALA FLYOVER',
    'flyover_charting': 'Charting',
    'flyover_charting_sub': 'Your Route',
    'flyover_plotting': 'Plotting waypoints',
    'flyover_stop': 'STOP',
    'flyover_stops': 'STOPS',
    'flyover_day': 'DAY',
    'flyover_paused': 'PAUSED',
    'flyover_label': 'FLYOVER',
    'flyover_fly': 'FLY',
    'flyover_pause': 'PAUSE',
    'flyover_resume': 'RESUME',
    'flyover_reset': 'RESET',
    'flyover_replay': 'REPLAY',
    'flyover_complete': 'COMPLETE',
    'flyover_journey_mapped': 'Journey Mapped',
    'flyover_stops_label': 'stops',
    'flyover_days_label': 'days',
    'flyover_loading_maps': 'Loading Maps…',
    'flyover_street_view': 'STREET VIEW',
    'flyover_sv_expand': 'Expand',
    'flyover_sv_minimize': 'Minimize',
    'flyover_sv_close': 'Close Street View',
    'flyover_sv_hint': 'Drag to look around · Click arrows to move',
    'flyover_explore_map': 'Drag to explore the map',
    'flyover_night': 'NIGHT',
    'flyover_dawn': 'DAWN',
    'flyover_morning': 'MORNING',
    'flyover_midday': 'MIDDAY',
    'flyover_afternoon': 'AFTERNOON',
    'flyover_evening': 'EVENING',

    'history_enter_era': 'Enter Era',
    'history_back_timeline': 'Back to Timeline',
    'history_archive_protocol': 'Archive Protocol',
    'history_archives': 'Kendala Archives',
    'history_timelines': 'Timelines',
    'history_scroll_drive': 'Scroll to Drive',
    'history_toc': 'Table of Contents',
    'history_visual_archive': 'Visual Archive',
    'history_end_record': 'End of Record',

    'planner_magic': 'Magic',
    'planner_route': 'Route',
    'planner_untitled': 'Untitled Trip',
    'planner_auto_generate': 'Auto-Generate Itinerary',
    'planner_ai_analyzing': 'Analyzing travel patterns...',
    'planner_ai_finding': 'Finding top-rated local experiences...',
    'planner_ai_constructing': 'Constructing your personalized itinerary...',

    'culture_archive_label': 'Kendala Cultural Archive',
    'culture_heritage_doc': 'Heritage Documentation',

    'map_loading_config': 'Loading Map Config...',

    'authenticating': 'Authenticating...',
    'syncing_cultural': 'Syncing Cultural Streams...',
    'back_to_timeline': 'Back to Timeline',
    'timelines_title': 'Timelines',

    'lang_code': 'en',
  },
};

// Fallback so consumers outside provider (e.g. during HMR) don't crash
const fallbackContext: LanguageContextType = {
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => translations.en[key] ?? key,
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  return context ?? fallbackContext;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('language');
      if (saved && ['kz', 'ru', 'en'].includes(saved)) {
        return saved as Language;
      }
    } catch {}
    return 'en'; // Default for rendering, but NOT saved until user explicitly selects
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('language', lang);
    } catch {}
  };

  const t = (key: string) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
