/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wrxtnfwckeqhwfjsaifh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyeHRuZndja2VxaHdmanNhaWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1ODgxMzEsImV4cCI6MjA4NDE2NDEzMX0.A7wWYKe7fALVx6v_NeTJqnMmLtQ8m-Rmx-RBHKiqkn0"