import { ALL_NEWS } from './components/data/news_data';

export interface Instrument {
  name: string;
  description: string;
  history: string;
  image: string;
  specs: Record<string, string>;
}

// ------------------------------------------------------------------
// REAL DATA GENERATION - PART 1 (EXPANDED 1-15) & PART 2 (STANDARD 16-50)
// ------------------------------------------------------------------

const REAL_STAYS = [
  // --- PART 1: EXPANDED DETAILED ENTRIES (1-15) ---
  {
    id: 'STAY-001',
    name_en: 'Shymbulak Mountain Resort',
    name_ru: 'ГЛК «Шымбулак»',
    name_kz: '«Шымбұлақ» ТШК',
    type_en: 'Resort', type_ru: 'Курорт', type_kz: 'Курорт',
    image: 'https://images.unsplash.com/photo-1706791407917-16bbb51e2cac?q=80&w=1080',
    price: 450, rating: '4.9',
    region_en: 'Almaty', region_ru: 'Алматы', region_kz: 'Алматы',
    description_en: 'Shymbulak Mountain Resort is the crown jewel of Central Asian alpine tourism, perched at an altitude of 2,260 meters in the picturesque Zailiysky Alatau gorge. This world-class destination offers a seamless blend of adrenaline and relaxation, featuring FIS-certified ski slopes that challenge professionals and gentle runs for beginners. Beyond skiing, guests can indulge in high-altitude dining at the "S.N.e.G" restaurant, experience the thrill of night skiing on floodlit tracks, or simply breathe in the crisp mountain air while paragliding over the valley. In summer, the resort transforms into a trekking paradise with routes leading to the Bogdanovich Glacier, offering breathtaking panoramas of the city below.',
    description_ru: 'Горнолыжный курорт «Шымбулак» — жемчужина альпийского туризма Центральной Азии, расположенная на высоте 2260 метров в живописном ущелье Заилийского Алатау. Это направление мирового класса предлагает идеальное сочетание адреналина и релаксации, предлагая сертифицированные FIS лыжные трассы, которые бросают вызов профессионалам, и пологие спуски для новичков. Помимо катания на лыжах, гости могут насладиться высокогорной кухней в ресторане «S.N.e.G», испытать острые ощущения от ночного катания на освещенных трассах или просто вдохнуть свежий горный воздух, летая на параплане над долиной. Летом курорт превращается в рай для треккинга с маршрутами, ведущими к леднику Богдановича, откуда открываются захватывающие панорамы города.',
    description_kz: '«Шымбұлақ» тау шаңғысы курорты — Іле Алатауының көркем шатқалында, 2260 метр биіктікте орналасқан Орталық Азияның альпілік туризмінің жауһары. Бұл әлемдік деңгейдегі демалыс орны кәсіпқойларға арналған FIS сертификатталған шаңғы трассалары мен жаңадан бастаушыларға арналған жайлы беткейлерді ұсына отырып, адреналин мен демалыстың тамаша үйлесімін сыйлайды. Шаңғы тебуден бөлек, қонақтар «S.N.e.G» мейрамханасында жоғары талғамды тағамдардан дәм татып, түнгі жарықтандырылған трассаларда сырғанаудан ләззат ала алады немесе аңғар үстімен парапланмен ұша отырып, таза тау ауасымен тыныстай алады. Жазда курорт Богданович мұздығына апаратын маршруттары бар треккинг жұмағына айналып, қаланың ғажайып панорамасын ұсынады.',
    contacts: { phone: '+7 (727) 331-77-77', email: 'info@shymbulak.com', web: 'shymbulak.com' },
    specs: { checkIn: '14:00', altitude: '2260m', season: 'Year-round', slopes: '25km' },
    inclusions: ['Gondola Access', 'Breakfast', 'Ski Locker', 'Spa Access']
  },
  {
    id: 'STAY-002',
    name_en: 'Rixos Borovoe',
    name_ru: 'Rixos Borovoe',
    name_kz: 'Rixos Borovoe',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1765533778985-a2f4419c12e0?q=80&w=1080',
    price: 600, rating: '5.0',
    region_en: 'Burabay', region_ru: 'Бурабай', region_kz: 'Бурабай',
    description_en: 'Situated on the serene shores of Lake Shchuchye within the Burabay National Park, Rixos Borovoe is a sanctuary of five-star luxury surrounded by ancient pine forests. The hotel architecture harmoniously integrates with the natural landscape, offering guests a unique combination of wilderness and opulence. Facilities include a world-class spa with Turkish hammams, an indoor swimming pool, and the region’s only legal casino. Whether you are looking for a family vacation with dedicated kids’ clubs or a romantic getaway in the "Switzerland of Kazakhstan," Rixos Borovoe provides impeccable service, gourmet dining options, and a gateway to exploring the mystical legends of the local mountains.',
    description_ru: 'Расположенный на спокойных берегах озера Щучье в национальном парке Бурабай, Rixos Borovoe представляет собой оазис пятизвездочной роскоши в окружении вековых сосновых лесов. Архитектура отеля гармонично вписывается в природный ландшафт, предлагая гостям уникальное сочетание дикой природы и великолепия. Удобства включают спа-центр мирового класса с турецкими хаммамами, крытый бассейн и единственное в регионе легальное казино. Ищете ли вы семейный отдых с детскими клубами или романтическое уединение в «Казахстанской Швейцарии», Rixos Borovoe предлагает безупречный сервис, изысканную кухню и ворота к изучению мистических легенд местных гор.',
    description_kz: 'Бурабай ұлттық паркіндегі Шортанды көлінің тыныш жағалауында орналасқан Rixos Borovoe — ғасырлық қарағайлы ормандар қоршауындағы бес жұлдызды сән-салтанат мекені. Қонақ үй сәулеті табиғи ландшафтпен үйлесім тауып, қонақтарға жабайы табиғат пен сән-салтанаттың бірегей үйлесімін ұсынады. Инфрақұрылымға түрік хаммамдары бар әлемдік деңгейдегі спа-орталық, жабық бассейн және аймақтағы жалғыз заңды казино кіреді. Балалар клубтары бар отбасылық демалыс немесе «Қазақстан Швейцариясындағы» романтикалық саяхат болсын, Rixos Borovoe мінсіз қызмет, дәмді тағамдар және жергілікті таулардың мистикалық аңыздарын зерттеу мүмкіндігін ұсынады.',
    contacts: { phone: '+7 (71636) 201-00', email: 'borovoe@rixos.com', web: 'rixos.com' },
    specs: { checkIn: '15:00', rooms: '200', view: 'Lake/Forest', spa: 'Anjana' },
    inclusions: ['Spa & Wellness', 'Casino Entry', 'Kids Club', 'Breakfast']
  },
  {
    id: 'STAY-003',
    name_en: 'Ethno-Aul Gunmy',
    name_ru: 'Этно-аул «Гунны»',
    name_kz: '«Гұндар» этно-ауылы',
    type_en: 'Yurt Camp', type_ru: 'Юрточный лагерь', type_kz: 'Киіз үй қалашығы',
    image: 'https://images.unsplash.com/photo-1651515089125-e73c19f1dedf?q=80&w=1080',
    price: 150, rating: '4.8',
    region_en: 'Almaty Region', region_ru: 'Алматинская обл.', region_kz: 'Алматы облысы',
    description_en: 'Ethno-Aul "Gunmy" offers a profound journey back in time, allowing guests to fully immerse themselves in the nomadic lifestyle of the Great Steppe. Located in the picturesque Talgar gorge, the camp features authentic felt yurts decorated with traditional ornaments and carpets. It is a living museum where history comes alive: guests can participate in archery, watch spectacular horse-riding stunts like "Kyz Kuu," and learn ancient crafts such as felt making. The culinary experience is equally authentic, with meals prepared over open fires including beshbarmak and fresh kumys. This is not just a stay; it is a cultural pilgrimage into the soul of the Kazakh people.',
    description_ru: 'Этно-аул «Гунны» предлагает глубокое путешествие во времени, позволяя гостям полностью погрузиться в кочевой образ жизни Великой Степи. Расположенный в живописном Талгарском ущелье, лагерь предлагает аутентичные войлочные юрты, украшенные традиционными орнаментами и коврами. Это живой музей, где оживает история: гости могут поучаствовать в стрельбе из лука, посмотреть захватывающие конные трюки, такие как «Кыз куу», и научиться древним ремеслам, например, валянию войлока. Кулинарный опыт столь же аутентичен: блюда готовятся на открытом огне, включая бешбармак и свежий кумыс. Это не просто отдых, это культурное паломничество в душу казахского народа.',
    description_kz: '«Гұндар» этно-ауылы қонақтарға Ұлы Даланың көшпенді өмір салтына толық енуге мүмкіндік беретін уақытқа саяхат ұсынады. Талғардың көркем шатқалында орналасқан лагерь дәстүрлі ою-өрнектермен және кілемдермен безендірілген шынайы киіз үйлерді ұсынады. Бұл — тарих тірілетін тірі мұражай: қонақтар садақ атуға қатыса алады, «Қыз қуу» сияқты әсерлі ат ойындарын тамашалап, киіз басу сияқты ежелгі қолөнерді үйрене алады. Ашық отта дайындалған бесбармақ пен жаңа сауылған қымызды қоса алғанда, ұлттық тағамдар да ерекше әсер қалдырады. Бұл жай ғана демалыс емес, бұл қазақ халқының жанына жасалған мәдени зиярат.',
    contacts: { phone: '+7 (701) 321-88-88', email: 'gunny@nomads.kz', web: 'ethnogunny.kz' },
    specs: { checkIn: '12:00', style: 'Nomadic', capacity: '4-6', activities: 'Culture' },
    inclusions: ['Horse Show', 'Archery Masterclass', '3 Meals (Halal)', 'Costume Photo']
  },
  {
    id: 'STAY-004',
    name_en: 'Tenir Eco Hotels',
    name_ru: 'Эко-отель Tenir',
    name_kz: 'Tenir эко-қонақ үйі',
    type_en: 'Eco-Lodge', type_ru: 'Эко-лодж', type_kz: 'Эко-лодж',
    image: 'https://images.unsplash.com/photo-1591870510273-8933a02b397c?q=80&w=1080',
    price: 380, rating: '4.9',
    region_en: 'Shymbulak', region_ru: 'Шымбулак', region_kz: 'Шымбұлақ',
    description_en: 'Tenir Eco Hotels represents the pinnacle of high-altitude luxury, situated at 3,200 meters above sea level. This unique glamping experience consists of stand-alone modular cabins with floor-to-ceiling panoramic windows, offering unobstructed views of the majestic Trans-Ili Alatau peaks. Accessible only via the Shymbulak gondola, the hotel ensures complete privacy and silence above the clouds. Each cabin is equipped with smart home systems, a personal sauna, and terrace, blending modern minimalism with the raw beauty of the mountains. It is a ski-in/ski-out location in winter and a stargazing haven in summer, perfect for those seeking solitude and connection with the cosmos.',
    description_ru: 'Tenir Eco Hotels представляет собой вершину высокогорной роскоши, расположенную на высоте 3200 метров над уровнем моря. Этот уникальный глэмпинг состоит из отдельных модульных домиков с панорамными окнами от пола до потолка, откуда открывается беспрепятственный вид на величественные пики Заилийского Алатау. Доступный только по канатной дороге Шымбулака, отель гарантирует полную п��иватность и тишину выше облаков. Каждый домик оснащен системой «умный дом», персональной сауной и террасой, сочетая современный минимализм с дикой красотой гор. Зимой это место формата ski-in/ski-out, а летом — рай для наблюдения за звездами, идеально подходящий для тех, кто ищет уединения и связи с космосом.',
    description_kz: 'Tenir Eco Hotels теңіз деңгейінен 3200 метр биіктікте орналасқан, биік таулы сән-салтанаттың шыңын білдіреді. Бұл бірегей глэмпинг еденнен төбеге дейінгі панорамалық терезелері бар жеке модульдік үйлерден тұрады, олардан Іле Алатауының асқақ шыңдарына тамаша көрініс ашылады. Тек Шымбұлақ аспалы жолымен қолжетімді қонақ үй бұлттардан жоғарыда толық құпиялылық пен тыныштықты қамтамасыз етеді. Әр үйшік «Ақылды үй» жүйесімен, жеке саунамен және террасамен жабдықтал��ан, бұл заманауи минимализмді таулардың табиғи сұлулығымен үйлестіреді. Қыста бұл ski-in/ski-out форматындағы орын болса, жазда жұлдыздарды тамашалайтын жұмаққа айналады.',
    contacts: { phone: '+7 (727) 331-77-77', email: 'stay@tenir.kz', web: 'tenirhotels.com' },
    specs: { checkIn: '14:00', altitude: '3200m', access: 'Gondola', tech: 'Smart Home' },
    inclusions: ['Gondola Pass', 'Private Sauna', 'Breakfast Delivery', 'Star Map']
  },
  {
    id: 'STAY-005',
    name_en: 'Oi-Qaragai',
    name_ru: 'Курорт «Ой-Карагай»',
    name_kz: '«Ой-Қарағай» курорты',
    type_en: 'Resort', type_ru: 'Курорт', type_kz: 'Курорт',
    image: 'https://images.unsplash.com/photo-1726096524099-909ab801abd4?q=80&w=1080',
    price: 220, rating: '4.7',
    region_en: 'Almaty Region', region_ru: 'Алматинская обл.', region_kz: 'Алматы облысы',
    description_en: 'Oi-Qaragai is a whimsical all-season mountain resort that feels like stepping into a fairy tale. Famous for its "Village on Trees" where guests stay in cozy treehouses elevated above the forest floor, the resort also offers luxurious chalets and traditional yurts. It is home to the largest yurt in the world and an extensive activity park featuring ziplines, rope courses, and mountain bike trails. The resort places a strong emphasis on family-friendly adventures and ecological harmony. With its professional horse center and ethnography programs, Oi-Qaragai provides a rich, multi-faceted experience that celebrates both the natural environment and Kazakh culture.',
    description_ru: '«Ой-Карагай» — это причудливый всесезонный горный курорт, словно сошедший со страниц сказки. Известный своей «Деревней на деревьях», где гости живут в уютных домиках, поднятых над лесной подстилкой, курорт также предлагает роскошные шале и традиционные юрты. Здесь находится самая большая юрта в мире и обширный парк развлечений с зиплайнами, веревочными трассами и трассами для горных велосипедов. Курорт делает сильный акцент на семейных приключениях и экологической гармонии. Благодаря профессиональному конному центру и этнографическим программам, «Ой-Карагай» предоставляет богатый, многогранный опыт, прославляющий как природную среду, так и казахскую культуру.',
    description_kz: '«Ой-Қарағай» — ертегі әлеміне енгендей әсер қалдыратын, жыл бойы жұмыс істейтін ерекше тау курорты. Қонақтар орман үстіндегі жайлы ағаш үйлерде тұратын «Ағаш ауылымен» танымал курорт сондай-ақ сәнді шалелер мен дәстүрлі киіз үйлерді ұсынады. Мұнда әлемдегі ең үлкен киіз үй және зиплайндары, арқан жолдары мен тау велосипеді трассалары бар ауқымды ойын-сауық паркі орналасқан. Курорт отбасылық шытырман оқиғалар мен экологиялық үйлесімділікке үлкен мән береді. Кәсіби ат орталығы мен этнографиялық бағдарламалары бар «Ой-Қарағай» табиғи орта мен қазақ мәдениетін дәріптейтін бай әрі жан-жақты демалысты ұсынады.',
    contacts: { phone: '+7 (727) 350-00-00', email: 'info@oiqaragai.kz', web: 'oi-qaragai.kz' },
    specs: { checkIn: '14:00', type: 'Mixed', area: 'Forest', unique: 'Treehouses' },
    inclusions: ['Activity Park Pass', 'Trolley Bus', 'Breakfast', 'Bike Rental']
  },
  {
    id: 'STAY-006',
    name_en: 'Ritz-Carlton Astana',
    name_ru: 'Ритц-Карлтон Астана',
    name_kz: 'Ritz-Carlton Astana',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1695551366637-b9103526ae11?q=80&w=1080',
    price: 550, rating: '5.0',
    region_en: 'Astana', region_ru: 'Астана', region_kz: 'Астана',
    description_en: 'Occupying the prestigious Talan Towers, The Ritz-Carlton, Astana is the epitome of modern luxury in the heart of Kazakhstan’s capital. The hotel offers sweeping views of the city’s futuristic skyline, including the Baiterek Tower, from its elegantly appointed rooms and suites. Culinary excellence is at the forefront, with the Mökki restaurant serving farm-to-table cuisine and the Selfie Bar offering bespoke cocktails on the 18th floor. The hotel also features a luxurious spa retreat and extensive event spaces. Every detail reflects a commitment to sophistication, making it the preferred address for dignitaries, business leaders, and discerning travelers visiting Astana.',
    description_ru: 'Занимающий престижные башни Talan Towers, The Ritz-Carlton, Astana является воплощением современной роскоши в самом сердце столицы Казахстана. Из элегантно обставленных номеров и люксов отеля открывается панорамный вид на футуристический горизонт города, включая монумент Байтерек. Кулинарное мастерство стоит на первом месте: ресторан Mökki предлагает блюда «от фермы к столу», а бар Selfie на 18-м этаже — авторские коктейли. В отеле также есть роскошный спа-центр и обширные пространства для мероприятий. Каждая деталь отражает приверженность изысканности, делая его предпочтительным адресом для высокопоставленных лиц, бизнес-лидеров и взыскательных путешественников, посещающих Астану.',
    description_kz: 'Беделді Talan Towers ғимаратында орналасқан The Ritz-Carlton, Astana — Қазақстан астанасының қақ ортасындағы заманауи сән-салтанаттың үлгісі. Қонақ үйдің талғампаз бөлмелері мен люкстерінен қаланың футуристикалық келбетіне, соның ішінде Бәйтерек монументіне ғажап көрініс ашылады. Аспаздық шеберлік басты орында: Mökki мейрамханасы фермерлік өнімдерден дайындалған тағамдарды ұсынса, 18-қабаттағы Selfie бары авторлық коктейльдерді ұсынады. Қонақ үйде сонымен қатар сәнді спа-орталық және іс-шараларға арналған кең залдар бар. Әрбір деталь талғампаздыққа деген адалдықты көрсетеді, бұл оны Астанаға келетін ресми тұлғалар, бизнес көшбасшылары және талғампаз саяхатшылар үшін ең қолайлы мекенге айналдырады.',
    contacts: { phone: '+7 (7172) 734-000', email: 'rc.tse@ritzcarlton.com', web: 'ritzcarlton.com' },
    specs: { checkIn: '15:00', location: 'City Center', stars: '5', dining: 'Mökki/Selfie' },
    inclusions: ['Club Lounge Access', 'Butler Service', 'Spa Access', 'Airport Transfer']
  },
  {
    id: 'STAY-007',
    name_en: 'Scout Glamping',
    name_ru: 'Глэмпинг Scout',
    name_kz: 'Scout глэмпингі',
    type_en: 'Glamping', type_ru: 'Глэмпинг', type_kz: 'Глэмпинг',
    image: 'https://images.unsplash.com/photo-1658509942695-ba0fe6453ffb?q=80&w=1080',
    price: 90, rating: '4.6',
    region_en: 'Akkol', region_ru: 'Акколь', region_kz: 'Ақкөл',
    description_en: 'Scout Glamping is a community-focused retreat hidden within the aromatic pine forests of Akkol. Designed for those seeking a digital detox and a return to simple pleasures, the camp offers comfortable safari tents with proper bedding and heating. The experience is centered around outdoor connection: guests gather for communal bonfires, watch movies under the stars at the open-air cinema, and explore forest trails on bicycles. It retains the spirit of a scout camp but adds the comfort of a hotel, creating a nostalgic yet modern escape perfect for friends, creative retreats, and families wanting to unplug and reconnect with nature.',
    description_ru: 'Scout Glamping — это ориентированный на сообщество ретрит, спрятанный в ароматных сосновых лесах Акколя. Созданный для тех, кто ищет цифровой детокс и возвращение к простым радостям, лагерь предлагает комфортабельные сафари-тенты с полноценными постелями и обогревом. Опыт сосредоточен на связи с природой: гости собираются у общих костров, смотрят фильмы под звездами в кинотеатре под открытым небом и исследуют лесные тропы на велосипедах. Он сохраняет дух скаутского лагеря, но добавляет комфорт отеля, создавая ностальгический, но современный побег, идеальный для друзей, творческих ретритов и семей, желающих отключиться от сети и воссоединиться с природой.',
    description_kz: 'Scout Glamping — Ақкөлдің хош иісті қарағайлы ормандарында жасырынған, қауымдастыққа бағытталған демалыс орны. Цифрлық детокс пен қарапайым қуаныштарды іздегендерге арналған лагерь жайлы төсек-орыны мен жылыту жүйесі бар сафари шатырларын ұсынады. Демалыс табиғатпен байланысқа негізделген: қонақтар ортақ алау басында жиналып, ашық аспан астындағы кинотеатрда жұлдыздар астында кино көреді және велосипедпен орман соқпақтарын аралайды. Ол скаут лагерінің рухын сақтай отырып, қонақ үй жайлылығын қосады, бұл достар, шығармашылық ретриттер және табиғат аясында демалғысы келетін отбасылар үшін ностальгиялық әрі заманауи демалыс орны.',
    contacts: { phone: '+7 (701) 555-44-33', email: 'hello@scout.kz', web: 'scoutglamping.kz' },
    specs: { checkIn: '14:00', vibe: 'Community', season: 'Summer', forest: 'Pine' },
    inclusions: ['Bike Rental', 'Cinema Under Stars', 'BBQ Kit', 'Marshmallows']
  },
  {
    id: 'STAY-008',
    name_en: 'Kolsay Lakes Village',
    name_ru: 'Гостевой дом «Кольсай»',
    name_kz: '«Көлсай» қонақ үйі',
    type_en: 'Guest House', type_ru: 'Гостевой дом', type_kz: 'Қонақ үйі',
    image: 'https://images.unsplash.com/photo-1644620426342-471c3ed4e1d4?q=80&w=1080',
    price: 70, rating: '4.5',
    region_en: 'Saty', region_ru: 'Саты', region_kz: 'Саты',
    description_en: 'Kolsay Lakes Village offers an authentic window into Kazakh rural life in the village of Saty, the gateway to the magnificent Kolsay Lakes and Lake Kaindy. These charming guest houses are run by local families who welcome visitors with genuine hospitality and delicious home-cooked organic meals. The accommodations are simple but cozy, featuring traditional decor and warm wood interiors. It serves as the perfect base camp for hikers and nature lovers. After a long day of trekking to the "Pearls of the Northern Tien Shan," guests can relax in a traditional Russian banya (sauna) and enjoy tea in the garden while gazing at the starry mountain sky.',
    description_ru: 'Kolsay Lakes Village предлагает аутентичное знакомство с казахской сельской жизнью в поселке Саты, воротах к великолепным озерам Кольсай и озеру Каинды. Этими очаровательными гостевыми домами управляют местные семьи, которые встречают посетителей с искренним гостеприимством и вкусной домашней органической едой. Жилье простое, но уютное, с традиционным декором и теплыми деревянными интерьерами. Это идеальный базовый лагерь для хайкеров и любителей природы. После долгого дня похода к «Жемчужинам Северного Тянь-Шаня» гости могут расслабиться в традиционной русской бане и насладиться чаем в саду, любуясь звездным горным небом.',
    description_kz: 'Kolsay Lakes Village Саты ауылындағы қазақ ауылының өмірімен шынайы танысуды ұсынады, бұл — ғажайып Көлсай көлдері мен Қайыңды көліне апаратын қақпа. Бұл сүйкімді қонақ үйлерді жергілікті отбасылар басқарады, олар келушілерді шынайы қонақжайлылықпен және дәмді үй тағамдарымен қарсы алады. Жатын орындар қарапайым, бірақ жайлы, дәстүрлі нақышта және жылы ағаш интерьермен безендірілген. Бұл жаяу туристер мен табиғат сүйер қауым үшін таптырмас базалық лагерь. «Солтүстік Тянь-Шань маржандарына» жасалған ұзақ жорықтан кейін қонақтар дәстүрлі моншада демалып, бақшада шай ішіп, таудың жұлдызды аспанын тамашалай алады.',
    contacts: { phone: '+7 (702) 221-11-00', email: 'saty@kolsay.kz', web: 'kolsay-village.kz' },
    specs: { checkIn: 'Flexible', meals: 'Included', host: 'Local Family', banya: 'Available' },
    inclusions: ['3 Home-cooked Meals', 'Banya Access', 'Local Guide', 'Tea Ceremony']
  },
  {
    id: 'STAY-009',
    name_en: 'Hotel Kazakhstan',
    name_ru: 'Гостиница «Казахстан»',
    name_kz: '«Қазақстан» қонақ үйі',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1705272230338-918683dbcbc4?q=80&w=1080',
    price: 100, rating: '4.4',
    region_en: 'Almaty', region_ru: 'Алматы', region_kz: 'Алматы',
    description_en: 'Standing tall as an enduring symbol of Almaty, the Hotel Kazakhstan is a triumph of Soviet modernist architecture. Built in the late 1970s, this 26-story skyscraper with its iconic golden crown was an engineering marvel of its time, designed to withstand the region’s seismic activity. Today, it offers a nostalgic yet comfortable stay in the city center. The balconies provide some of the best panoramic views of the Trans-Ili Alatau mountains. Its location is unbeatable for urban explorers, being steps away from the Abay Palace of Republic and the cable car station to Kok Tobe hill. Staying here is like inhabiting a piece of living history.',
    description_ru: 'Возвышаясь как вечный символ Алматы, гостиница «Казахстан» является триумфом советского модернизма. Построенный в конце 1970-х годов, этот 26-этажный небоскреб со знаменитой золотой короной был инженерным чудом своего времени, спроектированным для сейсмической активности региона. Сегодня он предлагает ностальгический, но комфортный отдых в центре города. С балконов открываются одни из лучших панорамных видов на горы Заилийского Алатау. Его расположение идеально для исследователей города: в шаге от Дворца Республики и станции канатной дороги на Кок-Тобе. Остановиться здесь — значит прикоснуться к живой истории.',
    description_kz: 'Алматының мәңгілік символы ретінде бой көтерген «Қазақстан» қонақ үйі — кеңестік модернистік сәулет өнерінің жеңісі. 1970 жылдардың соңында салынған, төбесінде әйгілі алтын тәжі бар бұл 26 қабатты зәулім ғимарат өз заманының инженерлік ғажайыбы болды және аймақтың сейсмикалық белсенділігіне төтеп беру үшін арнайы жобаланған. Бүгінде ол қала орталығында ностальгиялық әрі жайлы демалыс ұсынады. Балкондардан Іле Алатауының ең жақсы панорамалық көріністері ашылады. Оның орналасқан жері қала зерттеушілері үшін өте қолайлы: Республика сарайы мен Көктөбеге апаратын аспалы жол станциясының жанында. Мұнда тоқтау — тірі тарихтың бір бөлігіне айналу деген сөз.',
    contacts: { phone: '+7 (727) 291-91-01', email: 'book@kazakhstanhotel.kz', web: 'kazakhstanhotel.kz' },
    specs: { checkIn: '14:00', built: '1977', height: '102m', style: 'Soviet Modernism' },
    inclusions: ['Breakfast with View', 'Kok Tobe Access', 'Retro Bar Entry', 'City Map']
  },
  {
    id: 'STAY-010',
    name_en: 'Tethys Glamping',
    name_ru: 'Глэмпинг Tethys',
    name_kz: 'Tethys глэмпингі',
    type_en: 'Glamping', type_ru: 'Глэмпинг', type_kz: 'Глэмпинг',
    image: 'https://images.unsplash.com/photo-1762255107395-bcb83548e83f?q=80&w=1080',
    price: 180, rating: '4.8',
    region_en: 'Almaty Region', region_ru: 'Алматинская обл.', region_kz: 'Алматы облысы',
    description_en: 'Tethys Glamping offers a futuristic escape into the wild, inspired by the ancient ocean that once covered this land. Located on a vast steppe plateau, the camp consists of white geodesic domes that look like a colony on Mars. Each pod is a luxurious habitat with air conditioning, designer furniture, and private bathrooms. The highlight is the transparent section of the dome and the personal telescopes provided, making it a premier destination for astrotourism. Away from city lights, the Milky Way shines with unparalleled brightness. It is a romantic and serene hideaway where modern comfort meets the eternal silence of the steppe.',
    description_ru: 'Tethys Glamping предлагает футуристический побег в дикую природу, вдохновленный древним океаном, который когда-то покрывал эти земли. Расположенный на обширном степном плато, лагерь состоит из белых геодезических куполов, напоминающих колонию на Марсе. Каждая капсула — это роскошное жилище с кондиционером, дизайнерской мебелью и собственной ванной комнатой. Изюминкой является прозрачная секция купола и предоставляемые персональные телескопы, что делает это место главным направлением для астротуризма. Вдали от городских огней Млечный Путь сияет здесь с беспрецедентной яркостью. Это романтичное и спокойное убежище, где современный комфорт встречается с вечной тишиной степи.',
    description_kz: 'Tethys Glamping бір кездері осы жерді жауып жатқан ежелгі мұхиттан шабыт алған, жабайы табиғатқа футуристік саяхатты ұсынады. Кең дала үстіртінде орналасқан лагерь Марстағы колонияға ұқсайтын ақ геодезиялық күмбездерден тұрады. Әр капсула — кондиционер, дизайнерлік жиһаз және жеке жуынатын бөлмесі бар сәнді баспана. Күмбездің мөлдір бөлігі мен ұсынылатын жеке телескоптар оны астротуризмнің басты орталығына айналдырады. Қала шамдарынан алыс жерде Құс жолы ерекше жарық болып көрінеді. Бұл — заманауи жайлылық пен даланың мәңгілік тыныштығы тоғысқан романтикалық әрі тыныш мекен.',
    contacts: { phone: '+7 (707) 111-22-33', email: 'space@tethys.kz', web: 'tethys.kz' },
    specs: { checkIn: '15:00', theme: 'Space', view: 'Steppe/Stars', extra: 'Telescopes' },
    inclusions: ['Telescope Usage', 'Breakfast in Bed', 'Welcome Drink', 'Astro-Guide']
  },
  {
    id: 'STAY-011',
    name_en: 'The St. Regis Astana',
    name_ru: 'The St. Regis Astana',
    name_kz: 'The St. Regis Astana',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1760454220991-ca0577d5bd6a?q=80&w=1080',
    price: 700, rating: '5.0',
    region_en: 'Astana', region_ru: 'Астана', region_kz: 'Астана',
    description_en: 'The St. Regis Astana is a palatial hotel located in the Central Park of Astana, on the banks of the Ishim River. It blends the legacy of the St. Regis brand with Kazakh cultural heritage. The hotel is renowned for its signature Butler Service, ensuring that every guest\'s preference is met with precision. Interiors feature a grand staircase, original art pieces, and a luxurious Iridium Spa. Guests can enjoy the ritual of afternoon tea or saber champagne in the evening. It is the address for royalty and elite travelers, offering a secluded yet central location with unparalleled elegance and grandeur.',
    description_ru: 'The St. Regis Astana — это отель-дворец, расположенный в Центральном парке Астаны, на берегу реки Ишим. Он сочетает в себе наследие бренда St. Regis с казахским культурным наследием. Отель славится своим фирменным сервисом дворецких, гарантирующим, что каждое предпочтение гостя будет выполнено с точностью. Интерьеры украшают грандиозная лестница, оригинальные произведения искусства и роскошный спа-центр Iridium. Гости могут насладиться ритуалом послеобеденного чая или сабражем шампанского вечером. Это адрес для королеских особ и элитных путешественников, предлагающий уединенное, но центральное расположение с непревзойденной элегантностью и величием.',
    description_kz: 'The St. Regis Astana — Астананың Орталық саябағында, Есіл өзенінің жағасында орналасқан сарай тәрізді қонақ үй. Ол St. Regis брендінің мұрасын қазақ мәдени мұрасымен ұштастырады. Қонақ үй әр қонақтың қалауының мүлтіксіз орындалуын қамтамасыз ететін фирмалық дворецкий қызметімен танымал. Интерьерінде зәулім баспалдақ, бірегей өнер туындылары және сәнді Iridium спа-орталығы бар. Қонақтар түстен кейінгі шәй рәсімінен немесе кешкі шампан сабражынан ләззат ала алады. Бұл — патшалар мен элиталық саяхатшыларға арналған мекен, ол оңаша, бірақ орталықта орналасқан теңдессіз талғампаздық пен ұлылықты ұсынады.',
    contacts: { phone: '+7 (7172) 790-888', email: 'astana.stregis@stregis.com', web: 'stregisastana.com' },
    specs: { checkIn: '15:00', location: 'Riverfront', stars: '5', service: 'Butler' },
    inclusions: ['Butler Service', 'Afternoon Tea', 'Spa Access', 'Shoe Shine']
  },
  {
    id: 'STAY-012',
    name_en: 'Rixos Water World Aktau',
    name_ru: 'Rixos Water World Aktau',
    name_kz: 'Rixos Water World Aktau',
    type_en: 'Resort', type_ru: 'Курорт', type_kz: 'Курорт',
    image: 'https://images.unsplash.com/photo-1729708790933-181ab8d90e0c?q=80&w=1080',
    price: 450, rating: '4.8',
    region_en: 'Aktau', region_ru: 'Актау', region_kz: 'Ақтау',
    description_en: 'Rixos Water World Aktau is the first and only five-star "All Inclusive" resort on the Caspian Sea coast of Kazakhstan. This sprawling complex is a destination in itself, featuring a pristine sandy beach, a massive theme park with water slides and attractions, and numerous pools including an infinity pool overlooking the sea. The resort caters to both families and couples, offering world-class entertainment, concerts, and diverse dining options ranging from Turkish to Asian cuisine. It has redefined beach tourism in the region, bringing the Turkish Riviera experience to the unique shores of the Caspian.',
    description_ru: 'Rixos Water World Aktau — первый и единственный пятизвездочный курорт «Все включено» на побережье Каспийского моря в Казахстане. Этот огромный комплекс сам по себе является достопримечательностью, предлагая чистейший песчаный пляж, огромный тематический парк с водными горками и аттракционами, а также множество бассейнов, включая инфинити-бассейн с видом на море. Курорт ориентирован как на семьи, так и на пары, предлагая развлечения мирового класса, концерты и разнообразные варианты питания от турецкой до азиатской кухни. Он переосмыслил пляжный туризм в регионе, предлагая опыт Турецкой Ривьеры на уникальных берегах Каспия.',
    description_kz: 'Rixos Water World Aktau — Қазақстанның Каспий теңізі жағалауындағы «Барлығы қосылған» жүйесі бойынша жұмыс істейтін алғашқы және жалғыз бес жұлдызды курорт. Бұл үлкен кешеннің өзі — көрікті жер, мұнда таза құмды жағажай, су горкалары мен аттракциондары бар үлкен тақырыптық парк және теңізге қарайтын инфинити-бассейнді қоса алғанда, түрлі бассейндер бар. Курорт отбасылар мен жұптарға арналған, мұнда әлемдік деңгейдегі ойын-сауық, концерттер және түрік асханасынан азиялық тағамдарға дейін түрлі тамақтану орындары ұсынылады. Ол аймақтағы пляж туризмін жаңа деңгейге көтеріп, Каспийдің ерекше жағалауында Түрік Ривьерасының тәжірибесін ұсынады.',
    contacts: { phone: '+7 (7292) 217-777', email: 'aktau@rixos.com', web: 'rixos.com/aktau' },
    specs: { checkIn: '14:00', beach: 'Private', board: 'All-Inclusive', park: 'Water World' },
    inclusions: ['All Inclusive Dining', 'Water Park Access', 'Concerts', 'Mini Club']
  },
  {
    id: 'STAY-013',
    name_en: 'Swissôtel Wellness Alatau',
    name_ru: 'Swissôtel Wellness Alatau',
    name_kz: 'Swissôtel Wellness Alatau',
    type_en: 'Resort', type_ru: 'Курорт', type_kz: 'Курорт',
    image: 'https://images.unsplash.com/photo-1639483059199-a1f650046e34?q=80&w=1080',
    price: 350, rating: '4.9',
    region_en: 'Almaty', region_ru: 'Алматы', region_kz: 'Алматы',
    description_en: 'Nestled in the lush foothills of Almaty, Swissôtel Wellness Resort Alatau is a sanctuary dedicated to holistic health and relaxation. Occupying a historic building that was once a renowned sanatorium, it has been completely revitalized to offer Swiss hospitality standards. The resort features thermal mineral springs, a medical wellness center offering diagnostics and treatments, and vast parklands for walking. The Purovel Spa & Sport facilities are state-of-the-art. It is the ideal escape for those looking to rejuvenate their body and mind while surrounded by tranquil nature, yet remaining close to the city center.',
    description_ru: 'Расположенный в пышных предгорьях Алматы, Swissôtel Wellness Resort Alatau — это святилище, посвященное целостному здоровью и релаксации. Занимая историческое здание, которое когда-то было известным санаторием, он был полностью обновлен, чтобы предложить стандарты швейцарского гостеприимства. Курорт располагает термальными минеральными источниками, медицинским велнес-центром, предлагающим диагностику и лечение, и обширными парковыми зонами для прогулок. Объекты Purovel Spa & Sport являются самыми современными. Это идеальное место для тех, кто хочет омолодить тело и разум в окружении спокойной природы, оставаясь при этом недалеко от центра города.',
    description_kz: 'Алматының жасыл бөктерінде орналасқан Swissôtel Wellness Resort Alatau — бұл толыққанды денсаулық пен демалысқа арналған мекен. Бір кездері әйгілі санаторий болған тарихи ғимаратта орналасқан ол швейцариялық қонақжайлылық стандарттарын ұсыну үшін толығымен жаңартылған. Курортта термалды минералды бұлақтар, диагностика мен емдеуді ұсынатын медициналық сауықтыру орталығы және серуендеуге арналған кең саябақтар бар. Purovel Spa & Sport нысандары ең заманауи үлгіде жасалған. Бұл — қала орталығына жақын бола тұра, тыныш табиғат аясында дене мен жанды жаңартуды қалайтындар үшін таптырмас орын.',
    contacts: { phone: '+7 (727) 391-01-01', email: 'almaty@swissotel.com', web: 'swissotel.com/almaty' },
    specs: { checkIn: '14:00', focus: 'Medical Wellness', water: 'Thermal Springs', forest: 'Park' },
    inclusions: ['Medical Consultation', 'Thermal Pool', 'Full Board', 'Fitness Classes']
  },
  {
    id: 'STAY-014',
    name_en: 'Qazaq Auyl Eco Hotel',
    name_ru: 'Эко-отель Qazaq Auyl',
    name_kz: 'Qazaq Auyl эко-қонақ үйі',
    type_en: 'Eco-Lodge', type_ru: 'Эко-лодж', type_kz: 'Эко-лодж',
    image: 'https://images.unsplash.com/photo-1719626503590-951a3f39d6b5?q=80&w=1080',
    price: 400, rating: '5.0',
    region_en: 'Medeu', region_ru: 'Медеу', region_kz: 'Медеу',
    description_en: 'Qazaq Auyl Eco Hotel is a stunning architectural reinterpretation of the nomadic dwelling, located high in the mountains near the Medeu skating rink. The hotel consists of individual lodges that mimic the shape of yurts but are built with high-tech materials and enormous windows. The interiors are a masterclass in "Neo-Nomad" style, featuring bespoke furniture and premium amenities. The on-site restaurant serves elevated Kazakh cuisine that rivals fine dining establishments. It offers a secluded, high-end experience that honors tradition while embracing the future, all set against the dramatic backdrop of the Trans-Ili Alatau.',
    description_ru: 'Эко-отель Qazaq Auyl — это потрясающая архитектурная реинтерпретация жилища кочевников, расположенная высоко в горах рядом с катком Медеу. Отель состоит из отдельных домиков, имитирующих форму юрт, но построенных из высокотехнологичных материалов с огромными окнами. Интерьеры представляют собой мастер-класс в стиле «Нео-номад», с мебелью на заказ и премиальными удобствами. В ресторане на территории подают блюда высокой казахской кухни, не уступающие лучшим заведениям. Это уединенный отдых высокого класса, который чтит традиции и устремлен в будущее, и все это на фоне драматических пейзажей Заилийского Алатау.',
    description_kz: 'Qazaq Auyl эко-қонақ үйі — Медеу мұз айдыны маңында, таудың биік бөктерінде орналасқан көшпенділер баспанасының таңғажайып сәулеттік жаңғыруы. Қонақ үй киіз үй пішініне ұқсайтын, бірақ жоғары технологиялық материалдардан және үлкен терезелерден салынған жеке үйшіктерден тұрады. Интерьерлері арнайы тапсырыспен жасалған жиһаздармен және премиум класты жабдықтармен «Нео-номад» стилінде жасалған. Мұндағы мейрамхана үздік мекемелермен бәсекелесе алатын жоғары деңгейлі қазақ асханасын ұсынады. Бұл — Іле Алатауының әсем көрінісі аясында дәстүрді құрметтей отырып, болашаққа ұмтылған оңаша әрі элиталық демалыс орны.',
    contacts: { phone: '+7 (727) 300-00-00', email: 'info@qazaqauyl.kz', web: 'qazaqauyl.kz' },
    specs: { checkIn: '14:00', location: 'Medeu', style: 'Neo-Nomad', dining: 'Gourmet' },
    inclusions: ['Gourmet Breakfast', 'Medeu Transfer', 'Welcome Tea', 'Private Terrace']
  },
  {
    id: 'STAY-015',
    name_en: 'The Veil Hotel',
    name_ru: 'Отель The Veil',
    name_kz: 'The Veil қонақ үйі',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1633510083374-4ee1dd978ede?q=80&w=1080',
    price: 300, rating: '4.8',
    region_en: 'Astana', region_ru: 'Астана', region_kz: 'Астана',
    description_en: 'The Veil Hotel is a landmark of avant-garde architecture in Astana, instantly recognizable by its fluid, waving façade. This boutique hotel is more than just a place to sleep; it is an immersive art object. Each room is uniquely designed with bespoke furnishings and artistic touches that challenge conventional hotel design. The complex houses several distinct dining venues, a wine boutique, and a spa, creating a curated lifestyle experience. It attracts the creative elite and those who appreciate bold design. Staying at The Veil is like living inside a sculpture, offering a completely different perspective on the capital city.',
    description_ru: 'Отель The Veil — это достопримечательность авангардной архитектуры в Астане, мгновенно узнаваемая по своему текучему, волнообразному фасаду. Этот бутик-отель — больше, чем просто место для ночлега; это иммерсивный арт-объект. Каждый номер имеет уникальный дизайн с мебелью на заказ и художественными штрихами, которые бросают вызов традиционному гостиничному дизайну. В комплексе расположено несколько отличных ресторанов, винный бутик и спа, создающих атмосферу кураторского образа жизни. Он привлекает творческую элиту и тех, кто ценит смелый дизайн. Остановиться в The Veil — значит жить внутри скульптуры, открывая совершенно иную перспективу на столицу.',
    description_kz: 'The Veil қонақ үйі — Астанадағы авангардтық сәулет өнерінің көрнекті үлгісі, ол өзінің толқынды, ерекше қасбетімен бірден көзге түседі. Бұл бутик-қонақ үй жай ғана түнейтін орын емес, бұл — иммерсивті өнер нысаны. Әр бөлме дәстүрлі қонақ үй дизайнына қарсы келетін арнайы жиһаздармен және көркемдік элементтермен ерекшеленеді. Кешенде бірнеше мейрамхана, шарап бутигі және спа бар, олар ерекше өмір салтын қалыптастырады. Ол шығармашылық элита мен батыл дизайнды бағалайтындарды қызықтырады. The Veil қонақ үйінде тоқтау — елордаға мүлдем басқа қырынан қарайтын мүсіннің ішінде өмір сүрумен тең.',
    contacts: { phone: '+7 (7172) 999-999', email: 'welcome@theveil.kz', web: 'theveil.kz' },
    specs: { checkIn: '14:00', style: 'Boutique', design: 'Avant-garde', art: 'Concept' },
    inclusions: ['Wine Tasting', 'Spa Treatment', 'Art Tour', 'Breakfast']
  },

  // --- PART 2: UPGRADED DETAILED ENTRIES (16-25) ---
  {
    id: 'STAY-016',
    name_en: 'Rakhmonov Springs',
    name_ru: 'Рахмоновские ключи',
    name_kz: 'Рахман қайнарлары',
    type_en: 'Sanatorium', type_ru: 'Санаторий', type_kz: 'Санаторий',
    image: 'https://images.unsplash.com/photo-1759651080652-f813b7098433?q=80&w=1080',
    price: 120, rating: '4.7',
    region_en: 'East Kazakhstan', region_ru: 'ВКО', region_kz: 'ШҚО',
    description_en: 'Hidden deep within the sacred Altai Mountains, near the four-state border, Rakhmonov Springs is a legendary sanctuary of healing and solitude. The resort is famous for its natural radon thermal springs, which bubble up at a perfect temperature amidst cedar forests and snow-capped peaks. Guests stay in comfortable wooden cottages that blend into the wilderness. The star attraction is the view of Mount Belukha, the highest peak in Siberia and Altai, often shrouded in mystical energy. It is a place for deep physical and spiritual rejuvenation, offering boat rides on the crystal-clear lake and hiking trails that feel like walking through untouched creation.',
    description_ru: 'Спрятанные глубоко в священных Алтайских горах, недалеко от границы четырех государств, Рахмоновские ключи — это легендарное святилище исцеления и уединения. Курорт знаменит своими природными радоновыми термальными источниками, бьющими среди кедровых лесов и заснеженных вершин. Гости проживают в комфортабельных деревянных коттеджах, сливающихся с дикой природой. Главной достопримечательностью является вид на гору Белуха, высочайшую вершину Сибири и Алтая, часто окутанную мистической энергией. Это место для глубокого физического и духовного омоложения, предлагающее лодочные прогулки по кристально чистому озеру и пешие тропы, напоминающие прогулку по нетронутому творению.',
    description_kz: 'Төрт мемлекеттің шекарасына жақын, қасиетті Алтай тауларының тереңінде жасырынған Рахман қайнарлары — емделу мен оңашаланудың аңызға айналған мекені. Курорт балқарағай ормандары мен қарлы шыңдар арасында атқылап жатқан табиғи радонды термалды бұлақтарымен танымал. Қонақтар жабайы табиғатпен үйлесім тапқан жайлы ағаш коттедждерде тұрады. Басты көрнекті жері — мистикалық қуатқа толы Сібір мен Алтайдың ең биік шыңы — Мұзтау көрінісі. Бұл — мөлдір таза көлде қайықпен серуендеуді және жаратылысы бұзылмаған табиғат аясындағы соқпақтармен жүруді ұсынатын, дене мен жанды терең сауықтыру орны.',
    contacts: { phone: '+7 (7232) 55-55-55', email: 'altay@rahmonov.kz', web: 'altaytravel.kz' },
    specs: { checkIn: '08:00', water: 'Radon', nature: 'Altai', view: 'Belukha' },
    inclusions: ['Radon Baths', '3 Meals (Organic)', 'Boat Ride', 'Doctor Consultation']
  },
  {
    id: 'STAY-017',
    name_en: 'Karavansaray Turkistan',
    name_ru: 'Karavansaray Turkistan',
    name_kz: 'Karavansaray Turkistan',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1579983291208-99ab7827fd5c?q=80&w=1080',
    price: 180, rating: '4.6',
    region_en: 'Turkistan', region_ru: 'Туркестан', region_kz: 'Түркістан',
    description_en: 'Located within the magnificent Karavansaray complex, this hotel invites guests to live inside a modern-day oriental fairy tale. The architecture pays homage to the Silk Road, featuring canals with gondolas, vibrant bazaars, and intricate tile work. The hotel itself offers luxurious rooms with views of the mesmerizing "Parade of Boats" show. Just a short walk from the UNESCO-listed Mausoleum of Khoja Ahmed Yasawi, it serves as the perfect base for cultural exploration. Guests can enjoy the "Flying Theater" attraction, relax in the themed spa, and dine on exquisite Central Asian cuisine, making every moment feel like a page from 1001 Nights.',
    description_ru: 'Расположенный внутри великолепного комплекса Караван-сарай, этот отель приглашает гостей пожить в современной восточной сказке. Архитектура отдает дань уважения Шелковому пути, с каналами, по которым плавают гондолы, яркими базарами и сложной плиткой. Сам отель предлагает роскошные номера с видом на завораживающее шоу «Парад лодок». Находясь всего в нескольких минутах ходьбы от мавзолея Ходжи Ахмеда Ясави, включенного в список ЮНЕСКО, он служит идеальной базой для культурного исследования. Гости могут посетить аттракцион «Летающий театр», расслабиться в тематическом спа и насладиться изысканной кухней Центральной Азии.',
    description_kz: 'Керуен-сарай кешенінің ішінде орналасқан бұл қонақ үй қонақтарды заманауи шығыс ертегісінде өмір сүруге шақырады. Сәулет өнері Жібек жолына құрмет көрсетеді: мұнда гондолалар жүзетін каналдар, жарқын базарлар және күрделі өрнектер бар. Қонақ үйдің өзі «Қайықтар шеруі» шоуына көрініс ашатын сәнді бөлмелерді ұсынады. ЮНЕСКО тізіміне енген Қожа Ахмет Ясауи кесенесінен қысқа қашықтықта орналасқандықтан, бұл мәдени зерттеулер үшін тамаша орын. Қонақтар «Ұшатын театр» аттракционын тамашалап, тақырыптық спада демалып, Орталық Азияның дәмді тағамдарынан дәм тата алады.',
    contacts: { phone: '+7 (72533) 50-50-50', email: 'booking@karavansaray.kz', web: 'karavansaray.com' },
    specs: { checkIn: '14:00', theme: 'Silk Road', location: 'Complex', show: 'Boat Parade' },
    inclusions: ['Flying Theater Ticket', 'Breakfast', 'Spa Access', 'Canal Boat Ride']
  },
  {
    id: 'STAY-018',
    name_en: 'Caspian Riviera Palace',
    name_ru: 'Caspian Riviera Palace',
    name_kz: 'Caspian Riviera Palace',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1687554829399-e5c2e89be9c5?q=80&w=1080',
    price: 250, rating: '4.8',
    region_en: 'Aktau', region_ru: 'Актау', region_kz: 'Ақтау',
    description_en: 'Carved directly into the limestone cliffs of the Caspian coast, Caspian Riviera Palace is a marvel of terraced engineering. This five-star hotel offers unparalleled connection to the sea, with a private marina and a multi-level deck for sunbathing. Its most famous feature is the large private aquarium housing sturgeon and other Caspian marine life. The rooms feature panoramic windows that frame spectacular sunsets over the water. The hotel exudes an atmosphere of exclusive seaside leisure, complete with a fine-dining seafood restaurant and an infinity pool that seems to merge with the horizon.',
    description_ru: 'Высеченный прямо в известняковых скалах Каспийского побережья, Caspian Riviera Palace является чудом террасной инженерии. Этот пятизвездочный отель предлагает непревзойденную связь с морем, располагая частной пристанью и многоуровневой палубой для принятия солнечных ванн. Его самая известная особенность — большой частный аквариум с осетрами и другой морской жизнью Каспия. Номера оснащены панорамными окнами, обрамляющими захватывающие закаты над водой. Отель излучает атмосферу эксклюзивного морского отдыха, дополненную рестораном морепродуктов высокой кухни и инфинити-бассейном, сливающимся с горизонтом.',
    description_kz: 'Каспий жағалауының әктас жартастарына қашалып салынған Caspian Riviera Palace — террасалық инженерияның ғажайыбы. Бұл бес жұлдызды қонақ үй теңізбен ерекше байланыс орнатып, жеке айлағы мен күнге қыздырынуға арналған көп деңгейлі палубасын ұсынады. Оның ең танымал ерекшелігі — бекіре және басқа да Каспий теңізінің жәндіктері мекендейтін үлкен жеке аквариум. Бөлмелерде су үстіндегі ғажайып күн батуын тамашалауға мүмкіндік беретін панорамалық терезелер бар. Қонақ үй теңіз өнімдері мейрамханасымен және көкжиекпен астасып жатқан инфинити-бассейнімен эксклюзивті теңіз демалысының атмосферасын сыйлайды.',
    contacts: { phone: '+7 (7292) 42-42-42', email: 'info@riviera.kz', web: 'caspianriviera.kz' },
    specs: { checkIn: '14:00', view: 'Sea Cliff', feature: 'Aquarium', pool: 'Infinity' },
    inclusions: ['Aquarium Tour', 'Private Beach', 'Breakfast', 'Sunset Cocktail']
  },
  {
    id: 'STAY-019',
    name_en: 'Royal Tulip Almaty',
    name_ru: 'Royal Tulip Almaty',
    name_kz: 'Royal Tulip Almaty',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1696766984569-a33d52748dba?q=80&w=1080',
    price: 400, rating: '4.7',
    region_en: 'Almaty', region_ru: 'Алматы', region_kz: 'Алматы',
    description_en: 'Royal Tulip Almaty represents the height of classic European elegance in the exclusive southern district of the city. Located on the road to Medeu, it is favored by diplomats and luxury travelers. The hotel interiors are lavish, featuring crystal chandeliers, marble floors, and grand ballrooms. The spacious rooms offer balconies with serene views of the Trans-Ili Alatau mountains. It is a popular venue for high-society weddings and international summits. Guests can relax in the opulent wellness center or enjoy high tea in the lounge, experiencing a level of service that recalls the golden age of hospitality.',
    description_ru: 'Royal Tulip Almaty представляет собой вершину классической европейской элегантности в эксклюзивном южном районе города. Расположенный по дороге на Медеу, он пользуется популярностью у дипломатов и люксовых путешественников. Интерьеры отеля роскошны: хрустальные люстры, мраморные полы и грандиозные бальные залы. Просторные номера располагают балконами с умиротворяющим видом на горы Заилийского Алатау. Это популярное место для светских свадеб и международных саммитов. Гости могут расслабиться в роскошном велнес-центре или насладиться чаепитием в лаундже, ощущая уровень сервиса, напоминающий золотой век гостеприимства.',
    description_kz: 'Royal Tulip Almaty қаланың эксклюзивті оңтүстік ауданындағы классикалық еуропалық талғампаздықтың шыңын білдіреді. Медеуге баратын жолда орналасқан бұл қонақ үй дипломаттар мен сәнді саяхатшылар арасында танымал. Қонақ үй интерьері хрусталь люстралармен, мәрмәр едендермен және зәулім балл залдарымен безендірілген. Кең бөлмелерде Іле Алатауының тыныш көрінісі ашылатын балкондар бар. Бұл — жоғары деңгейдегі үйлену тойлары мен халықаралық саммиттер өтетін танымал орын. Қонақтар сәнді сауықтыру орталығында демалып немесе лаунджда шай ішіп, қонақжайлылықтың алтын ғасырын еске түсіретін қызмет сапасын сезіне алады.',
    contacts: { phone: '+7 (727) 300-01-01', email: 'royal@tulip.kz', web: 'royaltulipalmaty.com' },
    specs: { checkIn: '14:00', style: 'Classic Baroque', location: 'Medeu Road', wellness: 'Luxury' },
    inclusions: ['High Tea', 'Spa Access', 'Welcome Fruit', 'Concierge 24/7']
  },
  {
    id: 'STAY-020',
    name_en: 'Menin Yurtim',
    name_ru: 'Моя Юрта (Menin Yurtim)',
    name_kz: 'Менің Юртым',
    type_en: 'Yurt Camp', type_ru: 'Юрточный лагерь', type_kz: 'Киіз үй қалашығы',
    image: 'https://images.unsplash.com/photo-1702920375620-24aa8b8e42f6?q=80&w=1080',
    price: 80, rating: '4.9',
    region_en: 'Charyn', region_ru: 'Чарын', region_kz: 'Шарын',
    description_en: 'Menin Yurtim is an authentic yurt camp located on the edge of the Charyn Canyon, offering a stark and beautiful contrast to the red rock formations. It provides a rare opportunity to sleep under the vast, unpolluted starry sky of the steppe. The yurts are comfortable, heated, and furnished with traditional Kazakh textiles. The camp operates on eco-friendly principles, using solar power and minimizing waste. Guests gather in the evenings around a communal fire to share stories and enjoy local cuisine. It is the perfect base for exploring the Valley of Castles at sunrise before the day-trippers arrive.',
    description_ru: 'Menin Yurtim — это аутентичный юрточный лагерь, расположенный на краю Чарынского каньона, создающий строгий и прекрасный контраст с красными скальными образованиями. Он предоставляет редкую возможность переночевать под огромным, незагрязненным звездным небом степи. Юрты комфортабельные, отапливаемые и обставлены традиционным казахским текстилем. Лагерь работает на принципах экологичности, используя солнечную энергию и минимизируя отходы. По вечерам гости собираются у общего костра, чтобы поделиться историями и насладиться местной кухней. Это идеальная база для исследования Долины Замков на рассвете, до прибытия однодневных туристов.',
    description_kz: 'Menin Yurtim — қызыл жартастармен әдемі үйлесім тапқан, Шарын шатқалының шетінде орналасқан шынайы киіз үй қалашығы. Ол даланың кең, таза жұлдызды аспаны астында түнеуге сирек мүмкіндік береді. Киіз үйлер жайлы, жылы және дәстүрлі қазақ тоқыма бұйымдарымен жабдықталған. Лагерь күн энергиясын пайдаланып, қалдықтарды азайту арқылы экологиялық таза қағидаттармен жұмыс істейді. Кешкісін қонақтар ортақ алау басына жиналып, әңгіме-дүкен құрып, жергілікті тағамдардан дәм татады. Бұл — күндізгі туристер келместен бұрын, таң сәріде Қамалдар алқабын аралауға таптырмас орын.',
    contacts: { phone: '+7 (777) 123-45-67', email: 'charyn@yurtim.kz', web: 'charyn.kz' },
    specs: { checkIn: '13:00', location: 'Canyon Edge', power: 'Solar', vibe: 'Wild' },
    inclusions: ['Canyon Guide', 'Breakfast', 'Firewood', 'Telescope Access']
  },
  {
    id: 'STAY-021',
    name_en: 'S.N.e.G Hotel',
    name_ru: 'Отель S.N.e.G',
    name_kz: 'S.N.e.G қонақ үйі',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1577138565519-b8bb9332ee49?q=80&w=1080',
    price: 200, rating: '4.8',
    region_en: 'Shymbulak', region_ru: 'Шымбулак', region_kz: 'Шымбұлақ',
    description_en: 'S.N.e.G (Sun, Nature, e-Glacier) is a boutique hotel and restaurant located at the Talgar Pass at an altitude of 3,200 meters. Accessible only by gondola or snowcat, it offers an exclusive high-altitude experience. The hotel has only a few rooms, ensuring privacy and personalized service. The terrace offers arguably the best view in the resort, looking down over the clouds and the city of Almaty. Guests enjoy the privilege of "First Tracks" — skiing down the pristine slopes before the lifts open to the public. The restaurant serves hearty alpine cuisine, making it a favorite spot for gourmets and mountain lovers.',
    description_ru: 'S.N.e.G (Солнце, Природа, Ледник) — это бутик-отель и ресторан, расположенный на Талгарском перевале на высоте 3200 метров. Доступный только на гондоле или ратраке, он предлагает эксклюзивный высокогорный опыт. В отеле всего несколько номеров, что гарантирует приватность и индивидуальный сервис. С террасы открывается, пожалуй, лучший вид на курорте — на облака и город Алматы внизу. Гости пользуются привилегией «Первый след» — спуск по нетронутым склонам до открытия подъемников для публики. Ресторан подает сытную альпийскую кухню, что делает его любимым местом гурманов и любителей гор.',
    description_kz: 'S.N.e.G (Күн, Табиғат, Мұздық) — Талғар асуында, 3200 метр биіктікте орналасқан бутик-қонақ үй және мейрамхана. Тек гондоламен немесе ратракпен жетуге болатын бұл орын эксклюзивті биік таулы демалысты ұсынады. Қонақ үйде санаулы ғана бөлме бар, бұл құпиялылық пен жеке қызметті қамтамасыз етеді. Террасадан бұлттар мен төмендегі Алматы қаласына керемет көрініс ашылады. Қонақтар «Алғашқы із» артықшылығына ие — аспалы жолдар көпшілікке ашылмас бұрын таза беткейлермен сырғанау мүмкіндігі. Мейрамхана құнарлы альпілік тағамдарды ұсынады, бұл оны гурмандар мен тау сүйер қауымның сүйікті орнына айналдырады.',
    contacts: { phone: '+7 (705) 111-22-33', email: 'sneg@shymbulak.kz', web: 'sneghotel.kz' },
    specs: { checkIn: '14:00', altitude: '3200m', access: 'Gondola/Ratrak', rooms: '6' },
    inclusions: ['First Tracks Skiing', 'Breakfast', 'Gondola Pass', 'Dinner Reservation']
  },
  {
    id: 'STAY-022',
    name_en: 'Altay Alps',
    name_ru: 'Алтайские Альпы',
    name_kz: 'Алтай Альпісі',
    type_en: 'Resort', type_ru: 'Курорт', type_kz: 'Курорт',
    image: 'https://images.unsplash.com/photo-1628534934930-c7a2e77c1267?q=80&w=1080',
    price: 100, rating: '4.5',
    region_en: 'East Kazakhstan', region_ru: 'ВКО', region_kz: 'ШҚО',
    description_en: 'Nestled in the deep forests of East Kazakhstan, Altay Alps is a ski resort renowned for its abundant snowfall and long winter season (November to April). It is a paradise for freeriders and those who love natural snow, often referred to as "powder." The accommodation consists of cozy wooden chalets and hotel blocks surrounded by birch and fir trees. The resort features a wellness center with pant (antler) baths, a traditional local therapy. Unlike the manicured slopes of Shymbulak, Altay Alps offers a more rustic, wild, and soulful skiing experience, perfect for true winter enthusiasts.',
    description_ru: 'Расположенный в глубоких лесах Восточного Казахстана, «Алтайские Альпы» — это горнолыжный курорт, известный своими обильными снегопадами и долгим зимним сезоном (с ноября по апрель). Это рай для фрирайдеров и любителей натурального снега, часто называемого «пухляком». Размещение состоит из уютных деревянных шале и гостиничных корпусов в окружении берез и елей. На курорте есть оздоровительный центр с пантовыми ваннами, традиционной местной терапией. В отличие от ухоженных трасс Шымбулака, «Алтайские Альпы» предлагают более рустикальный, дикий и душевный опыт катания, идеально подходящий для истинных энтузиастов зимы.',
    description_kz: 'Шығыс Қазақстанның қалың орманында орналасқан «Алтай Альпісі» — мол қарымен және ұзақ қысқы маусымымен (қарашадан сәуірге дейін) танымал тау шаңғысы курорты. Бұл фрирайдерлер мен табиғи қарды сүйетіндер үшін жұмақ. Орналастыру қайыңдар мен шыршалар қоршауындағы жайлы ағаш шалелер мен қонақ үй корпустарынан тұрады. Курортта дәстүрлі жергілікті емдеу әдісі — панты ванналары бар сауықтыру орталығы жұмыс істейді. Шымбұлақтың тегіс трассаларына қарағанда, «Алтай Альпісі» қысқы демалыстың нағыз жанкүйерлері үшін анағұрлым қарапайым, жабайы және жанға жайлы сырғанау тәжірибесін ұсынады.',
    contacts: { phone: '+7 (7232) 49-20-72', email: 'info@altay.kz', web: 'altay-alps.kz' },
    specs: { checkIn: '12:00', snow: 'Deep Powder', season: 'Nov-Apr', therapy: 'Pant Baths' },
    inclusions: ['Ski Pass', '3 Meals', 'Banya Access', 'Transfer from Ust-Kamenogorsk']
  },
  {
    id: 'STAY-023',
    name_en: 'Tree of Life Densaulyk',
    name_ru: 'Санаторий «Древо Жизни»',
    name_kz: '«Өмір ағашы» санаторийі',
    type_en: 'Sanatorium', type_ru: 'Санаторий', type_kz: 'Санаторий',
    image: 'https://images.unsplash.com/photo-1553003364-1835901e5a8a?q=80&w=1080',
    price: 150, rating: '4.3',
    region_en: 'Burabay', region_ru: 'Бурабай', region_kz: 'Бурабай',
    description_en: 'Tree of Life (Densaulyk) brings the concept of the Soviet sanatorium into the 21st century. Located in the healing microclimate of the Burabay pine forests, it combines modern medical diagnostics with natural therapies. The facility offers specialized programs for respiratory and musculoskeletal health, utilizing local mud and mineral water. Guests can enjoy comfortable rooms, a large swimming pool, and a dietary restaurant. It is a place where health is the priority, but comfort is not compromised, making it popular for families and seniors seeking a restorative holiday.',
    description_ru: '«Древо Жизни» (Денсаулык) переносит концепцию советского санатория в 21 век. Расположенный в целебном микроклимате сосновых лесов Бурабая, он сочетает современную медицинскую диагностику с природными методами лечения. Учреждение предлагает специализированные программы для здоровья дыхательных путей и опорно-двигательного аппарата, используя местные грязи и минеральную воду. Гости могут насладиться комфортабельными номерами, большим бассейном и диетическим рестораном. Это место, где здоровье в приоритете, но не в ущерб комфорту, что делает его популярным для семей и пожилых людей, ищущих восстановительный отдых.',
    description_kz: '«Өмір ағашы» (Денсаулық) кеңестік санаторий тұжырымдамасын 21-ғасырға бейімдейді. Бурабай қарағайлы ормандарының шипалы микроклиматында орналасқан ол заманауи медициналық диагностиканы табиғи емдеу әдістерімен ұштастырады. Мекеме жергілікті балшық пен минералды суды пайдалана отырып, тыныс алу және тірек-қимыл жүйесінің денсаулығына арналған арнайы бағдарламаларды ұсынады. Қонақтар жайлы бөлмелерде демалып, үлкен бассейн мен диеталық мейрамхананы пайдалана алады. Бұл — денсаулық басты орында тұратын, бірақ жайлылыққа нұқсан келмейтін, отбасылар мен сауықтыру демалысын іздеген қарттар арасында танымал орын.',
    contacts: { phone: '+7 (71636) 7-77-77', email: 'life@burabay.kz', web: 'densaulyk.kz' },
    specs: { checkIn: '12:00', focus: 'Medical Rehab', diet: 'Menu', pool: 'Indoor' },
    inclusions: ['Medical Check-up', 'Daily Procedures', '5 Meals/Day', 'Pool Access']
  },
  {
    id: 'STAY-024',
    name_en: 'Konakai Glamping',
    name_ru: 'Глэмпинг Konakai',
    name_kz: 'Konakai глэмпингі',
    type_en: 'Glamping', type_ru: 'Глэмпинг', type_kz: 'Глэмпинг',
    image: 'https://images.unsplash.com/photo-1761925280857-0edbb9f0f2ea?q=80&w=1080',
    price: 130, rating: '4.7',
    region_en: 'Almaty Region', region_ru: 'Алматинская обл.', region_kz: 'Алматы облысы',
    description_en: 'Konakai Glamping is a stylish collection of A-frame cabins situated on a high plateau in the Kaskelen Gorge. Designed for romance and relaxation, each cabin features a panoramic glass wall facing the valley and mountains. The signature amenity is the private "Furako" — a Japanese-style hot tub on the terrace of each cabin, allowing guests to soak in hot water while watching the snow fall or the sun set. The interiors are Scandi-chic, with cozy lofts and modern kitchenettes. It is a quick escape from the city that feels worlds away, perfect for couples and small groups of friends.',
    description_ru: 'Konakai Glamping — это стильная коллекция A-frame домиков, расположенных на высоком плато в Каскеленском ущелье. Созданный для романтики и релаксации, каждый домик имеет панорамную стеклянную стену, обращенную к долине и горам. Фирменным удобством является личное «Фурако» — горячая купель в японском стиле на террасе каждого домика, позволяющая гостям нежиться в горячей воде, наблюдая за снегопадом или закатом. Интерьеры выполнены в стиле сканди-шик, с уютными лофтами и современными мини-кухнями. Это быстрый побег из города, который кажется совершенно другим миром, идеально подходящий для пар и небольших компаний друзей.',
    description_kz: 'Konakai Glamping — Қаскелең шатқалындағы биік үстіртте орналасқан стильді A-frame үйлерінің топтамасы. Романтика мен демалысқа арналған әр үйдің аңғар мен тауларға қарайтын панорамалық шыны қабырғасы бар. Ерекшелігі — әр үйдің террасасындағы жеке «Фурако» жапон стиліндегі ыстық күбі, ол қонақтарға қардың жаууын немесе күннің батуын тамашалай отырып, ыстық суға түсуге мүмкіндік береді. Интерьері сканди-шик стилінде, жайлы лофттармен және заманауи шағын асүйлермен жабдықталған. Бұл — қаладан тез қашып шығып, мүлдем басқа әлемде жүргендей сезім сыйлайтын, жұптар мен шағын достар тобына арналған тамаша орын.',
    contacts: { phone: '+7 (707) 999-88-77', email: 'info@konakai.kz', web: 'konakai.kz' },
    specs: { checkIn: '14:00', tub: 'Private Furako', style: 'A-Frame', view: 'Panoramic' },
    inclusions: ['Furako Heating', 'Breakfast Basket', 'BBQ Grill', 'Marshmallows']
  },
  {
    id: 'STAY-025',
    name_en: 'Sheraton Astana',
    name_ru: 'Sheraton Astana',
    name_kz: 'Sheraton Astana',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1621275471769-e6aa344546d5?q=80&w=1080',
    price: 280, rating: '4.8',
    region_en: 'Astana', region_ru: 'Астана', region_kz: 'Астана',
    description_en: 'Ideally situated across from the Abu Dhabi Plaza and adjacent to the Botanical Garden, Sheraton Astana is a hub of connection in the capital. The hotel features contemporary design with Kazakh motifs and offers some of the best service in the city. The Emiliya Restaurant serves an exceptional breakfast, while the hotel\'s spa is a destination for urban wellness. It is particularly known for its vibrant lobby culture and business facilities. Whether attending a conference or exploring the nearby EXPO site, guests appreciate the seamless blend of functionality and comfort that Sheraton provides.',
    description_ru: 'Идеально расположенный напротив Abu Dhabi Plaza и рядом с Ботаническим садом, Sheraton Astana является центром притяжения в столице. Отель отличается современным дизайном с казахскими мотивами и предлагает один из лучших сервисов в городе. Ресторан Emiliya сервирует исключительный завтрак, а спа-центр отеля является местом для городского велнеса. Он особенно известен своей оживленной атмосферой в лобби и бизнес-услугами. Посещая конференцию или исследуя близлежащий комплекс ЭКСПО, гости ценят безупречное сочетание функциональности и комфорта, которое предоставляет Sheraton.',
    description_kz: 'Abu Dhabi Plaza-ға қарама-қарсы және Ботаникалық бақтың жанында өте қолайлы орналасқан Sheraton Astana — елордадағы байланыс орталығы. Қонақ үй қазақ нақыштары бар заманауи дизайнымен ерекшеленеді және қаладағы ең жақсы қызмет түрлерін ұсынады. Emiliya мейрамханасы ерекше таңғы ас ұсынады, ал қонақ үйдің спа-орталығы — қалалық сауықтыру орны. Ол әсіресе лоббидегі жанды атмосферасымен және бизнес қызметтерімен танымал. Конференцияға қатыса ма, әлде жақын маңдағы ЭКСПО аумағын аралай ма, қонақтар Sheraton ұсынатын функционалдылық пен жайлылықтың мінсіз үйлесімін жоғары бағалайды.',
    contacts: { phone: '+7 (7172) 60-60-60', email: 'sheraton.astana@sheraton.com', web: 'sheratonastana.com' },
    specs: { checkIn: '15:00', location: 'Botanical Garden', stars: '5', spa: 'Shine Spa' },
    inclusions: ['Breakfast Buffet', 'Spa Access', 'Gym', 'High-Speed Wi-Fi']
  },

  // --- PART 3: REMAINING STANDARD ENTRIES (26-50) ---
  {
    id: 'STAY-026',
    name_en: 'Wyndham Garden Burabay',
    name_ru: 'Wyndham Garden Burabay',
    name_kz: 'Wyndham Garden Burabay',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1758263589459-bd026b195430?q=80&w=1080',
    price: 180, rating: '4.6',
    region_en: 'Burabay', region_ru: 'Бурабай', region_kz: 'Бурабай',
    description_en: 'Contemporary hotel surrounded by nature. Perfect for families, with easy access to the lake and hiking trails.',
    description_ru: 'Современный отель в окружении природы. Идеально для семей, с легким доступом к озеру и пешеходным тропам.',
    description_kz: 'Табиғат аясындағы заманауи қонақ үй. Көлге және жаяу жүргіншілер жолына жақын, отбасыларға қолайлы.',
    contacts: { phone: '+7 (71636) 55-555', email: 'reservations@wyndham.kz' },
    specs: { checkIn: '14:00', style: 'Modern', access: 'Park' }
  },
  {
    id: 'STAY-027',
    name_en: 'Terrassa Park',
    name_ru: 'Terrassa Park',
    name_kz: 'Terrassa Park',
    type_en: 'Resort', type_ru: 'Курорт', type_kz: 'Курорт',
    image: 'https://images.unsplash.com/photo-1680246638284-0a34ea41cc76?q=80&w=1080',
    price: 140, rating: '4.5',
    region_en: 'Burabay', region_ru: 'Бурабай', region_kz: 'Бурабай',
    description_en: 'Popular lakeside resort in Burabay. Features a private beach, swimming pool, and comfortable family cottages.',
    description_ru: 'Популярный курорт на берегу озера в Бурабае. Частный пляж, бассейн и комфортабельные семейные коттеджи.',
    description_kz: 'Бурабайдағы көл жағасындағы танымал курорт. Жеке жағажай, бассейн және жайлы отбасылық коттедждер бар.',
    contacts: { phone: '+7 (71636) 4-44-44', email: 'info@terrassapark.kz' },
    specs: { checkIn: '14:00', beach: 'Lake', family: 'Yes' }
  },
  {
    id: 'STAY-028',
    name_en: 'Holiday Inn Aktau',
    name_ru: 'Holiday Inn Aktau',
    name_kz: 'Holiday Inn Aktau',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1697368761794-b25176d78a11?q=80&w=1080',
    price: 120, rating: '4.4',
    region_en: 'Aktau', region_ru: 'Актау', region_kz: 'Ақтау',
    description_en: 'Reliable comfort in Aktau city center. Sea views from upper floors, business facilities, and international standards.',
    description_ru: 'Надежный комфорт в центре Актау. Вид на море с верхних этажей, бизнес-услуги и международные стандарты.',
    description_kz: 'Ақтау орталығындағы сенімді жайлылық. Жоғарғы қабаттардан теңіз көрінісі, бизнес қызметтер және халықаралық стандарттар.',
    contacts: { phone: '+7 (7292) 29-00-00', email: 'aktau@holidayinn.com' },
    specs: { checkIn: '14:00', business: 'Yes', view: 'City/Sea' }
  },
  {
    id: 'STAY-029',
    name_en: 'Rixos Khadisha Shymkent',
    name_ru: 'Rixos Khadisha Shymkent',
    name_kz: 'Rixos Khadisha Shymkent',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1703820775340-b923e5929371?q=80&w=1080',
    price: 220, rating: '4.9',
    region_en: 'Shymkent', region_ru: 'Шымкент', region_kz: 'Шымкент',
    description_en: 'The most luxurious hotel in Southern Kazakhstan. Neoclassical architecture, superb spa, and warm southern hospitality.',
    description_ru: 'Самый роскошный отель Южного Казахстана. Неоклассическая архитектура, превосходный спа и теплое южное гостеприимство.',
    description_kz: 'Оңтүстік Қазақстандағы ең сәнді қонақ үй. Неоклассикалық архитектура, тамаша спа және оңтүстіктің жылы қонақжайлылығы.',
    contacts: { phone: '+7 (7252) 61-01-01', email: 'shymkent@rixos.com' },
    specs: { checkIn: '14:00', region: 'South', style: 'Grand' }
  },
  {
    id: 'STAY-030',
    name_en: 'Hampton by Hilton Turkistan',
    name_ru: 'Hampton by Hilton Turkistan',
    name_kz: 'Hampton by Hilton Turkistan',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1742497457950-6dd3236ee54d?q=80&w=1080',
    price: 90, rating: '4.5',
    region_en: 'Turkistan', region_ru: 'Туркестан', region_kz: 'Түркістан',
    description_en: 'Modern and convenient base for pilgrims and tourists. Located minutes away from the Mausoleum of Khoja Ahmed Yasawi.',
    description_ru: 'Современная и удобная база для паломников и туристов. В минутах ходьбы от мавзолея Ходжи Ахмеда Ясави.',
    description_kz: 'Зияратшылар мен туристерге арналған заманауи әрі ыңғайлы орын. Қожа Ахмет Ясауи кесенесіне бірнеше минуттық жерде.',
    contacts: { phone: '+7 (72533) 4-11-11', email: 'turkistan@hilton.com' },
    specs: { checkIn: '14:00', location: 'City', access: 'Walking' }
  },
  {
    id: 'STAY-031',
    name_en: 'Gorelnik Camping',
    name_ru: 'Кемпинг «Горельник»',
    name_kz: '«Горельник» кемпингі',
    type_en: 'Camping', type_ru: 'Кемпинг', type_kz: 'Кемпинг',
    image: 'https://images.unsplash.com/photo-1713860052825-4798abffb5b9?q=80&w=1080',
    price: 30, rating: '4.7',
    region_en: 'Almaty', region_ru: 'Алматы', region_kz: 'Алматы',
    description_en: 'Budget-friendly camping spot near the Gorelnik hot springs. Wooden platforms for tents and stunning mountain scenery.',
    description_ru: 'Бюджетный кемпинг у горячих источников Горельник. Деревянные настилы для палаток и потрясающие горные пейзажи.',
    description_kz: 'Горельник ыстық бұлақтары жанындағы қолжетімді кемпинг. Шатырларға арналған ағаш сәкілер және тау көрінісі.',
    contacts: { phone: '+7 (777) 000-00-00', email: 'camp@gorelnik.kz' },
    specs: { checkIn: 'Flexible', type: 'Tent', amenities: 'Springs' }
  },
  {
    id: 'STAY-032',
    name_en: 'Namaste Shambhala',
    name_ru: 'Ретрит-центр Namaste',
    name_kz: 'Namaste ретрит орталығы',
    type_en: 'Retreat', type_ru: 'Ретрит', type_kz: 'Ретрит',
    image: 'https://images.unsplash.com/photo-1757940113920-69e3686438d3?q=80&w=1080',
    price: 110, rating: '4.8',
    region_en: 'Almaty Region', region_ru: 'Алматинская обл.', region_kz: 'Алматы облысы',
    description_en: 'Yoga and meditation retreat center in the mountains. Vegetarian cuisine, silence vows, and panoramic yoga halls.',
    description_ru: 'Центр йоги и медитации в горах. Вегетарианская кухня, обеты молчания и панорамные залы для йоги.',
    description_kz: 'Таудағы йога және медитация орталығы. Вегетариандық тағамдар, тыныштық серті және панорамалық йога залдары.',
    contacts: { phone: '+7 (701) 108-108-1', email: 'om@namaste.kz' },
    specs: { checkIn: '14:00', focus: 'Yoga', food: 'Veg' }
  },
  {
    id: 'STAY-033',
    name_en: 'Shymbulak Chalet',
    name_ru: 'Шале Шымбулак',
    name_kz: 'Шымбұлақ Шале',
    type_en: 'Chalet', type_ru: 'Шале', type_kz: 'Шале',
    image: 'https://images.unsplash.com/photo-1623077129797-90f6189ddb76?q=80&w=1080',
    price: 800, rating: '5.0',
    region_en: 'Shymbulak', region_ru: 'Шымбулак', region_kz: 'Шымбұлақ',
    description_en: 'Exclusive private chalets right on the slopes. Fireplaces, private saunas, and direct ski access for VIP guests.',
    description_ru: 'Эксклюзивные частные шале прямо на склонах. Камины, личные сауны и прямой выход на лыжах для VIP-гостей.',
    description_kz: 'Трасса бойындағы эксклюзивті жеке шалелер. Каминдер, жеке сауналар және VIP қонақтар үшін шаңғымен тікелей шығу.',
    contacts: { phone: '+7 (777) 777-77-77', email: 'vip@shymbulak.kz' },
    specs: { checkIn: '15:00', privacy: 'High', luxury: 'Max' }
  },
  {
    id: 'STAY-034',
    name_en: 'InterContinental Almaty',
    name_ru: 'InterContinental Almaty',
    name_kz: 'InterContinental Almaty',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1552128436-05262280b292?q=80&w=1080',
    price: 320, rating: '4.7',
    region_en: 'Almaty', region_ru: 'Алматы', region_kz: 'Алматы',
    description_en: 'Classic luxury opposite the Presidential Palace. Beautiful gardens, famous Sunday brunch, and tennis courts.',
    description_ru: 'Классическая роскошь напротив Президентского дворца. Красивые сады, знаменитые воскресные бранчи и теннисные корты.',
    description_kz: 'Президент сарайына қарама-қарсы классикалық сән-салтанат. Әдемі бақтар, әйгілі жексенбілік бранчтар және теннис корты.',
    contacts: { phone: '+7 (727) 250-50-00', email: 'interconti@almaty.kz' },
    specs: { checkIn: '14:00', style: 'Grand', garden: 'Yes' }
  },
  {
    id: 'STAY-035',
    name_en: 'Hilton Astana',
    name_ru: 'Hilton Astana',
    name_kz: 'Hilton Astana',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1762341950661-36a6f230cb6a?q=80&w=1080',
    price: 260, rating: '4.6',
    region_en: 'Astana', region_ru: 'Астана', region_kz: 'Астана',
    description_en: 'Futuristic hotel located within the EXPO 2017 complex. Rooftop bar, extensive spa, and proximity to Mega Silk Way.',
    description_ru: 'Футуристический отель в комплексе ЭКСПО-2017. Руфтоп-бар, обширный спа и близость к Mega Silk Way.',
    description_kz: 'ЭКСПО-2017 кешеніндегі футуристік қонақ үй. Шатырдағы бар, үлкен спа және Mega Silk Way-ге жақындық.',
    contacts: { phone: '+7 (7172) 64-99-00', email: 'astana.info@hilton.com' },
    specs: { checkIn: '15:00', location: 'Expo', spa: 'Large' }
  },
  {
    id: 'STAY-036',
    name_en: 'Boutique Hotel Silk Road',
    name_ru: 'Бутик-отель «Шелковый Путь»',
    name_kz: '«Жібек Жолы» бутик-қонақ үйі',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1742973266609-7ef932ecd21a?q=80&w=1080',
    price: 110, rating: '4.5',
    region_en: 'Turkistan', region_ru: 'Туркестан', region_kz: 'Түркістан',
    description_en: 'Small boutique hotel with traditional decor. Hand-painted ceilings, oriental carpets, and a cozy courtyard.',
    description_ru: 'Небольшой бутик-отель с традиционным декором. Расписные потолки, восточные ковры и уютный внутренний дворик.',
    description_kz: 'Дәстүрлі нақыштағы шағын бутик-қонақ үй. Қолмен өрнектелген төбелер, шығыс кілемдері және жайлы аула.',
    contacts: { phone: '+7 (72533) 3-33-33', email: 'silkroad@turkistan.kz' },
    specs: { checkIn: '13:00', style: 'Oriental', size: 'Small' }
  },
  {
    id: 'STAY-037',
    name_en: 'Caspian Glamping',
    name_ru: 'Caspian Glamping',
    name_kz: 'Caspian глэмпингі',
    type_en: 'Glamping', type_ru: 'Глэмпинг', type_kz: 'Глэмпинг',
    image: 'https://images.unsplash.com/photo-1761872936161-9c2075a7ca11?q=80&w=1080',
    price: 140, rating: '4.7',
    region_en: 'Aktau', region_ru: 'Актау', region_kz: 'Ақтау',
    description_en: 'Luxury tents right on the sandy beach of the Caspian Sea. Fall asleep to the sound of waves and wake up to sunrise.',
    description_ru: 'Роскошные шатры прямо на песчаном берегу Каспия. Засыпайте под шум волн и просыпайтесь с рассветом.',
    description_kz: 'Каспийдің құмды жағалауындағы сәнді шатырлар. Толқын үнімен ұйықтап, күннің шығуымен ояныңыз.',
    contacts: { phone: '+7 (777) 888-99-00', email: 'sea@glamping.kz' },
    specs: { checkIn: '14:00', beach: 'Direct', view: 'Sea' }
  },
  {
    id: 'STAY-038',
    name_en: 'Edem Resort',
    name_ru: 'Курорт Edem',
    name_kz: 'Edem курорты',
    type_en: 'Resort', type_ru: 'Курорт', type_kz: 'Курорт',
    image: 'https://images.unsplash.com/photo-1664081393748-4deb342d0f5d?q=80&w=1080',
    price: 160, rating: '4.5',
    region_en: 'Burabay', region_ru: 'Бурабай', region_kz: 'Бурабай',
    description_en: 'A quiet resort in the woods of Burabay. Wooden chalets, indoor pool, and a calm atmosphere away from the crowds.',
    description_ru: 'Тихий курорт в лесах Бурабая. Деревянные шале, крытый бассейн и спокойная атмосфера вдали от толпы.',
    description_kz: 'Бурабай орманындағы тыныш курорт. Ағаш шалелер, жабық бассейн және қала шуынан алыс атмосфера.',
    contacts: { phone: '+7 (71636) 6-00-00', email: 'edem@burabay.kz' },
    specs: { checkIn: '14:00', vibe: 'Quiet', type: 'Forest' }
  },
  {
    id: 'STAY-039',
    name_en: 'Muz Tau Base Camp',
    name_ru: 'Базовый лагерь «Муз Тау»',
    name_kz: '«Мұз Тау» базалық лагері',
    type_en: 'Camp', type_ru: 'Лагерь', type_kz: 'Лагерь',
    image: 'https://images.unsplash.com/photo-1673694783311-4a7384f7f28c?q=80&w=1080',
    price: 50, rating: '4.9',
    region_en: 'East Kazakhstan', region_ru: 'ВКО', region_kz: 'ШҚО',
    description_en: 'The gateway to Mount Belukha. Essential for trekkers, offering sturdy shelter, guides, and equipment rental.',
    description_ru: 'Ворота к горе Белуха. Необходим для треккеров, предлагает надежное укрытие, гидов и прокат снаряжения.',
    description_kz: 'Мұзтау шыңына апаратын қақпа. Треккинг жасаушылар үшін пана, гидтер және жабдықтарды жалға алу мүмкіндігі.',
    contacts: { phone: '+7 (777) 333-22-11', email: 'belukha@altay.kz' },
    specs: { checkIn: 'Flexible', type: 'Expedition', altitude: 'High' }
  },
  {
    id: 'STAY-040',
    name_en: 'Grand Tien Shan Hotel',
    name_ru: 'Отель Grand Tien Shan',
    name_kz: 'Grand Tien Shan қонақ үйі',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1562407132-e23789f81bb7?q=80&w=1080',
    price: 150, rating: '4.3',
    region_en: 'Almaty', region_ru: 'Алматы', region_kz: 'Алматы',
    description_en: 'Historic hotel in the quiet center of Almaty. Known for its "Bali" spa, spacious rooms, and proximity to Zenkov Cathedral.',
    description_ru: 'Исторический отель в тихом центре Алматы. Известен спа-центром «Бали», просторными номерами и близостью к собору.',
    description_kz: 'Алматының тыныш орталығындағы тарихи қонақ үй. «Бали» спа-орталығымен, кең бөлмелерімен және соборға жақындығымен танымал.',
    contacts: { phone: '+7 (727) 244-96-00', email: 'info@tienshan.kz' },
    specs: { checkIn: '14:00', location: 'Old Center', spa: 'Bali' }
  },
  {
    id: 'STAY-041',
    name_en: 'Sunkar Falconry Lodge',
    name_ru: 'Лодж «Сункар»',
    name_kz: '«Сұңқар» лоджы',
    type_en: 'Lodge', type_ru: 'Лодж', type_kz: 'Лодж',
    image: 'https://images.unsplash.com/photo-1672939113761-f599cebb325f?q=80&w=1080',
    price: 130, rating: '4.6',
    region_en: 'Almaty', region_ru: 'Алматы', region_kz: 'Алматы',
    description_en: 'Located within the Sunkar raptor sanctuary. Guests can watch falconry shows and stay in stone cottages.',
    description_ru: 'Расположен в питомнике хищных птиц Сункар. Гости могут смотреть шоу соколиной охоты и жить в каменных коттеджах.',
    description_kz: 'Сұңқар құс тәлімбағында орналасқан. Қонақтар құсбегілік шоуын тамашалап, тас коттедждерде тұра алады.',
    contacts: { phone: '+7 (727) 300-11-22', email: 'sunkar@birds.kz' },
    specs: { checkIn: '14:00', theme: 'Birds', nature: 'Gorge' }
  },
  {
    id: 'STAY-042',
    name_en: 'Orbita Glamping',
    name_ru: 'Глэмпинг Orbita',
    name_kz: 'Orbita глэмпингі',
    type_en: 'Glamping', type_ru: 'Глэмпинг', type_kz: 'Глэмпинг',
    image: 'https://images.unsplash.com/photo-1614642240262-a452c2c11724?q=80&w=1080',
    price: 160, rating: '4.7',
    region_en: 'Almaty Region', region_ru: 'Алматинская обл.', region_kz: 'Алматы облысы',
    description_en: 'Spherical pods offering 360-degree views of the Trans-Ili Alatau. Located near the Big Almaty Lake road.',
    description_ru: 'Сферические капсулы с обзором 360 градусов на Заилийский Алатау. Расположены по дороге на БАО.',
    description_kz: 'Іле Алатауына 360 градус көрініс беретін сфералық капсулалар. Үлкен Алматы көліне барар жолда орналасқан.',
    contacts: { phone: '+7 (700) 555-66-77', email: 'orbita@glamp.kz' },
    specs: { checkIn: '14:00', shape: 'Sphere', view: 'Mountains' }
  },
  {
    id: 'STAY-043',
    name_en: 'The Dostyk Hotel',
    name_ru: 'Отель «Достык»',
    name_kz: '«Достық» қонақ үйі',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1765436271393-16377d973d0e?q=80&w=1080',
    price: 200, rating: '4.5',
    region_en: 'Almaty', region_ru: 'Алматы', region_kz: 'Алматы',
    description_en: 'A historic landmark preserving the grandeur of the past. Protected as an architectural monument, offering classic service.',
    description_ru: 'Историческая достопримечательность, сохраняющая величие прошлого. Памятник архитектуры с классическим сервисом.',
    description_kz: 'Өткеннің сәнін сақтаған тарихи ескерткіш. Сәулет ескерткіші ретінде қорғалатын, классикалық қызмет көрсететін орын.',
    contacts: { phone: '+7 (727) 333-30-00', email: 'dostyk@hotel.kz' },
    specs: { checkIn: '14:00', history: 'Monument', style: 'Retro' }
  },
  {
    id: 'STAY-044',
    name_en: 'Rixos President Astana',
    name_ru: 'Rixos President Astana',
    name_kz: 'Rixos President Astana',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1697368761794-b25176d78a11?q=80&w=1080',
    price: 350, rating: '4.8',
    region_en: 'Astana', region_ru: 'Астана', region_kz: 'Астана',
    description_en: 'The political and business hub of the capital. Luxurious rooms, high-security standards, and Irish Pub hospitality.',
    description_ru: 'Политический и деловой центр столицы. Роскошные номера, высокие стандарты безопасности и ирландский паб.',
    description_kz: 'Астананың саяси және іскерлік орталығы. Сәнді бөлмелер, қауіпсіздіктің жоғары стандарты және ирланд пабы.',
    contacts: { phone: '+7 (7172) 24-50-50', email: 'president@rixos.com' },
    specs: { checkIn: '14:00', secure: 'High', center: 'Diplomatic' }
  },
  {
    id: 'STAY-045',
    name_en: 'Lesnaya Skazka Cottages',
    name_ru: 'Коттеджи «Лесная Сказка»',
    name_kz: '«Лесная Сказка» коттедждері',
    type_en: 'Lodge', type_ru: 'Лодж', type_kz: 'Лодж',
    image: 'https://images.unsplash.com/photo-1762782778316-80b05d151915?q=80&w=1080',
    price: 280, rating: '4.7',
    region_en: 'Almaty Region', region_ru: 'Алматы', region_kz: 'Алматы облысы',
    description_en: 'Premium cottages in the Oi-Qaragai gorge. Stone and wood construction, fireplaces, and large terraces for families.',
    description_ru: 'Премиум коттеджи в ущелье Ой-Карагай. Камень и дерево, камины и большие террасы для семей.',
    description_kz: 'Ой-Қарағай шатқалындағы премиум коттедждер. Тас пен ағаштан жасалған, каминдері және отбасыларға арналған үлкен террасалары бар.',
    contacts: { phone: '+7 (727) 350-11-00', email: 'cottage@oiqaragai.kz' },
    specs: { checkIn: '15:00', size: 'Large', amenities: 'Fireplace' }
  },
  {
    id: 'STAY-046',
    name_en: 'Novotel Almaty City Center',
    name_ru: 'Novotel Almaty City Center',
    name_kz: 'Novotel Almaty City Center',
    type_en: 'Hotel', type_ru: 'Отель', type_kz: 'Қонақ үй',
    image: 'https://images.unsplash.com/photo-1754091152248-01b2e298635a?q=80&w=1080',
    price: 180, rating: '4.6',
    region_en: 'Almaty', region_ru: 'Алматы', region_kz: 'Алматы',
    description_en: 'Modern hotel at the intersection of Dostyk and Abay. Ideal for business and city exploration. Stylish design.',
    description_ru: 'Современный отель на пересечении Достык и Абая. Идеально для бизнеса и прогулок. Стильный дизайн.',
    description_kz: 'Достық пен Абай қиылысындағы заманауи қонақ үй. Бизнес және қала аралау үшін тамаша. Стильді дизайн.',
    contacts: { phone: '+7 (727) 355-55-55', email: 'h9555@accor.com' },
    specs: { checkIn: '14:00', style: 'Urban', chain: 'Accor' }
  }
];

export const localizedData: Record<string, any> = {
  en: {
    news: ALL_NEWS,
    stays: {
      title: 'Nomadic Stays',
      subtitle: 'Sanctuaries of The Steppe',
      filters: { all: 'All Horizons' },
      labels: {
        unitsMapped: 'Sanctuaries Mapped',
        threshold: 'Value Threshold',
        briefing: 'Sanctuary Briefing',
        specs: 'Technical Specifications',
        contact: 'Signal Frequencies',
        obligation: 'Energy Exchange',
        perCycle: 'Per Cycle',
        initiate: 'Initiate Booking'
      },
      items: REAL_STAYS.map(s => ({
        id: s.id,
        name: s.name_en,
        type: s.type_en,
        image: s.image,
        price: s.price,
        rating: s.rating,
        region: s.region_en,
        description: s.description_en,
        contacts: s.contacts,
        specs: s.specs,
        inclusions: (s as any).inclusions
      }))
    }
  },
  ru: {
    news: ALL_NEWS,
    stays: {
      title: 'Обители Кочевников',
      subtitle: 'Святилища Великой Степи',
      filters: { all: 'Все Горизонты' },
      labels: {
        unitsMapped: 'Объектов на карте',
        threshold: 'Порог Стоимости',
        briefing: 'Досье Убежища',
        specs: 'Технические Данные',
        contact: 'Частоты Связи',
        obligation: 'Энергообмен',
        perCycle: 'За Цикл',
        initiate: 'Начать Бронирование'
      },
      items: REAL_STAYS.map(s => ({
        id: s.id,
        name: s.name_ru,
        type: s.type_ru,
        image: s.image,
        price: s.price,
        rating: s.rating,
        region: s.region_ru,
        description: s.description_ru,
        contacts: s.contacts,
        specs: s.specs,
        inclusions: (s as any).inclusions
      }))
    }
  },
  kz: {
    news: ALL_NEWS,
    stays: {
      title: 'Көшпенділер Мекені',
      subtitle: 'Ұлы Даланың Қасиетті Орындары',
      filters: { all: 'Барлық Көкжиектер' },
      labels: {
        unitsMapped: 'Картадағы Нысандар',
        threshold: 'Құн Шегі',
        briefing: 'Пана туралы Мәлімет',
        specs: 'Техникалық Деректер',
        contact: 'Байланыс Жиіліктері',
        obligation: 'Қуат Алмасу',
        perCycle: 'Бір Цикл Үшін',
        initiate: 'Брондауды Бастау'
      },
      items: REAL_STAYS.map(s => ({
        id: s.id,
        name: s.name_kz,
        type: s.type_kz,
        image: s.image,
        price: s.price,
        rating: s.rating,
        region: s.region_kz,
        description: s.description_kz,
        contacts: s.contacts,
        specs: s.specs,
        inclusions: (s as any).inclusions
      }))
    }
  }
};
